.eslintrc.js, .gitignore, app/store/Personnel.js, app/view/main/Map.js, package.json
… only lints using eslint for now.
```
npm i
npm test
```
Preparation for a basic CI.
Please review.
=> Add basic node / npm test setup

app/view/main/Map.js
=> Add ZoomToMaxExtentButton from BasiGX

.eslintrc.js, app/factory/Layer.js, app/view/main/Map.js, data/layers/default.json
This adds a LayerFactory singleton to create OL layers from a JSON configuration. Supported layers at the moment:
- OSM
- WMS
- ESRI REST
=> Implement LayerFactory

app.json, app/view/LayerTree.js, app/view/main/Main.js
Hat-tip to @chrismayer for the awesome `mapready`-event idea.
=> Add an autoconnecting Layertree

app/view/header/Panel.js, app/view/main/Main.js
This adds a new header component with a dummy logo image.
=> Add a header component

app/view/main/Main.js, app/view/main/Map.js
=> Give Map component a semantic xtype

app/factory/Layer.js
This adds the following layer types to the `LayerFactory`:
- Bing
- World Wind (BlueMarble-200412)
- ArcGIS REST
See #10
=> Add more layer types to LayerFactory

app/factory/Layer.js
This adds support for single tile WMS layers (in addition to the tiled WMS layers) in the LayerFactory.
Closes #9
=> Support ImageWMS and TileWMS in LayerFactory

.gitignore, app/controller/MapController.js, app/view/main/Map.js
This PR adds a scale bar (Ol Control) to the map (bottom left corner).
In addition, the initialization of measure buttons, has been re-factored. Therefore, #37 has to be merged at first. 
See #22
=> Scaleline to map

app/controller/panel/TimeSlider.js, app/factory/Layer.js, app/view/toolbar/MapTools.js, resources/data/layers/default.json
This depends on https://github.com/terrestris/BasiGX/pull/372 and fixes #60
=> Add a UMN-based WFS layer which is timedependent

app/view/toolbar/MapTools.js
Resolves #72. 
Depends on https://github.com/terrestris/BasiGX/pull/425 (already merged).
Please review @chrismayer @weskamm
=> Implement Zoom in and Zoom Out by Box tool

app/controller/button/DigitizeButtonController.js
This removes the last drawn feature on an erroneous request and fixes access of an possibily unavailable key.
See #74.
Please review @annarieger.
=> Removes the last drawn feature on error and fixes a NPE

app/controller/button/SpatialQueryButton.js, app/factory/Layer.js, app/model/button/SpatialQueryButton.js, app/view/button/SpatialQueryButton.js, app/view/toolbar/MapTools.js, resources/data/layers/default.json
Introduces a new component `SpatialQueryButton` that uses `GeoExt.util.OGCFilter` to query a configured/associated layer with a spatial filter. A polygon, a linestring or a point can be drawn to define the geometry used in the filter.
Depends on https://github.com/geoext/geoext3/pull/566/ and https://github.com/terrestris/BasiGX/pull/497
Please note, that that queried WFS has CORS enabled or use NGinx proxy. 
In addition, the layer factory was enhanced to support  required fields for the name of geoemtry field and namespace definitions needed for WFS `GetFeature`.
```
"geomFieldName": "geometry",
"namespaceDefinitions": {
"osm": "http://terrestris"
}
```
Resolves https://github.com/compassinformatics/cpsi-mapview/issues/101
=> Spatial query tool

karma-conf.common.js, karma-watch.conf.js, package.json
Title says it all.
Follow up to #121.
In corporation with @chrismayer :+1:
=> Introduces config for karma watch mode

app.json
=> Add jsonix to js dependencies

app/plugin/TreeColumnInResolutionRange.js
=> Plugin TreeColumnInResolutionRange - fix line break detection

app/util/Legend.js
=> Fixup #132: Add missing LegendUtil class

app/controller/button/SpatialQueryButton.js, app/view/button/SpatialQueryButton.js
The config option triggerWfsRequest should be on the view not the controller
=> Move triggerWfsRequest property

app/factory/Layer.js
Ensure that any style and filter set on the vector layer is also set on the WMS layer when switching
=> Keep filters and styles when using the switch layer

app/util/Legend.js, app/view/layer/StyleSwitcherRadioGroup.js
Reuse LegendUtil.getWmsStyleFromSldFile
Fix a comment typo
=> Reuse Style Name function

app/controller/grid/Grid.js
Create a new menu each time so the correct context record is used. 
Destroy the menu when hidden as per [this post](https://www.sencha.com/forum/showthread.php?296731-5-1-0-107-ContextMenu-issue&p=1083634&viewfull=1#post1083634).
=> Fix zoom context menu

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js
Allows an existing map layer to be used with the CpsiMapview.controller.button.DigitizeButton
=> Allow resultLayer to be configured

resources/data/layers/default.json
This PR fixes the broken syntax of the layers configuration and corrects some indentation.
=> Fix broken layer configuration

app/view/grid/Grid.js
Controller refs need to be explicitly added
=> Add missing reference

app/controller/form/Login.js, app/view/form/Login.js, test/spec/view/form/Login.spec.js
Add a form mask when logging in.
=> Add Login mask

app/view/menuitem/LayerGrid.js
Move window settings to a config option
=> Add windowConfig property for LayerGrid

app/controller/grid/Grid.js
- Filter out nulls in column list which causes issues for WFS server
- Reset grid loading message after an Excel export
=> Minor grid fixes

app/controller/grid/Grid.js
Without this the grid is loaded twice when clearing paging
=> Clear all paging parameters

app/controller/toolbar/CircleSelectionToolbar.js
title says it all...
fixes #195
=> Fix circle radius bug

app/plugin/TreeColumnStyleSwitcher.js
Title says it all...
fixes #196
=> Render Radio Groups on LayerTree Initialisation

app/view/layer/StyleSwitcherRadioGroup.js, resources/data/layers/default.json, resources/data/styling/Test_Alternative_Gas_Style.xml
fixes #159 
- checks if a style in the config file has a provided title, if yes it will be applied to the layer tree
- but it is still allowed to provide no title
=> Add title property

package.json
Partially addresses #182 - will also need to update app.json
=> Add geostyler dependencies via node

azure-pipelines.yml
This:
- runs tests
- sets up SenchaCmd and creates a production build of the library
=> Add Azure-Pipelines CI

app/util/Legend.js
Fixes the broken WMS legend image for labelled layers.
Closes #209
=> Fix broken WMS legend image for labelled layers

app/model/grid/Grid.js, app/view/grid/Grid.js
=> Allow group edit button to be hidden

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js
This allows polygons to be captured more easily in an application as the layer can be passed into the tool from the parent view
=> Allow the draw layer to be set in the button config

app/controller/grid/Grid.js
Find any instances of the child form and check if they have the record already loaded. If this is the case then simply bring this form to the front, otherwise load the record into a new form.
=> Only open a new child form if the record is not already open

app/view/toolbar/CircleSelectionToolbar.js
Allow for easier styling of the toolbar
=> Add CSS class to Circle toolbar

app/controller/grid/Grid.js
This fixes hiding/showing the filter feature with the grid window.
=> Set vectorLayerKey property based on gridLayerName

app/util/Layer.js, app/view/menuitem/LayerRefresh.js
This handles refreshing OpenLayers layer types. These are used in a couple of places so have been extracted into a util class.
=> Create a new Layer util function 

app/field/Feature.js, app/util/WmsFilter.js
Ext.Assert is not available in production builds
=> Wrap asserts in debug

app/util/Layer.js
=> Handle cluster layer refresh

app/field/Feature.js
Check model dirty state is not altered from original state rather than not dirty
=> Check model dirty status is not changed by adding features on initial record load

app/form/field/YearField.js, app/view/field/YearField.js, app/view/grid/ItemDeleter.js
Event handler name made more generic
=> Item deleter event handler name fixed

app.json, app/view/window/MinimizableWindow.js, sass/src/view/LayerTree.scss
In relation to #315.
Switch theme. Fix baselayer radio buttons style. Remove sizer limitations on `CpsiMapview.view.window.MinimizableWindow`.
=> Apply Triton theme

app/plugin/FeatureInfoWindow.js, app/view/main/Map.js, resources/data/layers/default.json
Minor changes to the Feature Info window branch.
=> WMS Feature Info Window minor changes

app/view/grid/ItemDeleter.js
Itemdeleter constructor implemented as workaround for inheriting config values
=> Item deleter grid controller mixin debug

app/factory/Layer.js, resources/data/layers/default.json, resources/data/layers/tree.json
Resolves #265 
Warning: the diff from GitHub looks horrible. 
Actually, only the for-loop has been converted to a recursive function. Hence, the real change is not that big.
I noticed the layertree does not properly update the switch layer anymore. This seemed to be introduced with https://github.com/compassinformatics/cpsi-mapview/commit/081b0e71ca1d1e729bfedaf2cc964f6723291f1e
=> Enable switchlayer change in subfolder

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js, app/view/toolbar/MapTools.js
This PR introduces the following features:
* A context menu entry to clear the active group
* The possibility to move any point in the point digitize mode
* The possibility to delete any point in the point digitize mode
It also contains a refactoring that was necessary to provide this features.
Resolves: #252
Resolves: #253
Resolves: #88
=> Network solver tool updates

app/controller/button/SpatialQueryButton.js, app/controller/button/StreetViewTool.js, app/data/model/LayerTreeNode.js, app/factory/Layer.js, app/model/grid/Grid.js, app/view/grid/Grid.js, app/view/layer/StyleSwitcherRadioGroup.js
Various fixes for issues discovered when integrating all tools into a larger application. 
Mainly relating to requires and making sure `defaultClickEnabled` is set when using various tools. 
@JakobMiksch  - I added 41e74a2 as a temp fix for errors thrown in the layer switcher. 
Merging all now to give a demo of all the latest features but would appreciate a quick review.
=> Miscellaneous fixes

app/controller/grid/Grid.js
Currently the WMS filter is not reset when all filters are cleared.
=> Clear WMS Grid Filters

app/plugin/ExpandPanel.js
=> Expand panel plugin

app/view/grid/Grid.js
This allows a selection to be easily cleared in the grids
=> Allow deselection of features

app/field/Line.js
Width not set correctly for the line
=> Fix line styling

app/controller/grid/Grid.js
Also standardise line endings to LF
=> Restore any minimised windows so they can be brought to front

app/controller/button/DigitizeButtonController.js
Fires a custom `featuresupdated ` OpenLayers event on the vector layer source in the `CpsiMapview.controller.button.DigitizeButtonController`. 
This is useful in order to make new calculations based on features returned by the solver. It is possible to listen to `add`, `remove` events etc. on an GeoExt feature store associated with the `resultLayer`, however these are triggered for each feature, so if HTTP calls are created can become very numerous even if `autoAbort` is used (leading to lots of cancelled requests).
=> Sdd custom featuresupdated event to DigitizeButtonController

app/controller/button/DigitizeButtonController.js
=> Points are now clickable

app/controller/button/DigitizeButtonController.js
This pull request ensures the `modifications` is populated and sent when raising the `featuresupdated` event when the "Clear All" option is selected. 
The `clearActiveGroup` and `clearResultLayer` which both required this have been merged to avoid code duplication.
=> Pass modifications object when clearing layer in DigitizeButtonController

app/controller/button/SpatialQueryButton.js
Adds a context-menu as shown below to allow the feature and any spatial layer filter to be cleared.
=> Add context-menu clear filter tool to the Spatial Query tool

app/controller/grid/Grid.js
=> Ensure Grid columns are updated

sass/src/view/LayerTree.scss
Avoid large gaps between radio buttons for base layers
=> Update Layer tree baselayer CSS

app/model/FeatureEventsMixin.js
=> Fix array length check

app/controller/button/DigitizeButtonController.js
Linked to #378. This allows the `CpsiMapview.controller.button.DigitizeButtonController` and tool to be used to draw features in the browser without requiring back-end service calls. 
It could be written as a separate simpler tool, but using the same class allows enabled/disabled logic and configs to be reused.
=> Allow drawing of features without service calls

app/controller/button/DigitizeButtonController.js
This pull request allows the `drawLayer` and `resultLayer` to be changed after the tool has been created.
This is useful in the following scenario:
- a model has a feature store and is loaded into a form with a digitising tool
- the tool is created and `drawLayer` is set to the layer associated with the model's feature store
- the model is saved and loaded back into the store as a new model
- the model feature store now has a different layer, but the tool on the form points to the previously created layer, and the tools no longer work
Allowing the tool's layers to be changed fixes this with the new `setDrawLayer` and `setResultLayer` functions.
To allow these to work all map interactions using the `drawLayer` were moved to individual functions so they can be removed and recreated on a …
=> Allow Digitising Tool Layers to be Changed

resources/data/layers/default.json
Add attribution and a maxScale setting to the sample layers, and fix several of the WFS URLs.
=> Demo fixes

app/factory/Layer.js
Fixes: https://github.com/compassinformatics/cpsi-mapview/issues/382
Needs some testing.
=> introduce image aborting

.nojekyll, README.md, app.json
See https://stackoverflow.com/questions/43481269/github-pages-404-on-node-modules-folder
=> Allow files from node_modules to be used on GH pages

app/view/main/Main.js
=> Allow tools panel to be resizeable

app/controller/button/MinimizeAllButtonController.js, app/view/button/MinimizeAllButton.js, app/view/toolbar/MapFooter.js
This adds a new `cmv_minimize_all_button`. Somehow the FontAwesome glyph does not work. I tested it with different glyphs that worked, but https://fontawesome.com/v4.7/icon/window-minimize did not. I tried to use the code that was listed on the page under `unicode` maybe that was wrong. Do you know more @geographika ?
Fixes #420
=> Minimize all

app/controller/grid/Grid.js
Switch layers can have 2 layer keys defined but only one active
=> Check for both WMS and WFS layers in grid

app/controller/grid/Grid.js
- Add a `force` flag to ensure layers are refreshed when underlying data is changed. 
- Remove duplicated code
=> Refactor refreshing of associated layers and grid store

app.json, app/Application.js, app/util/ApplicationMixin.js
Without this update the mouse control coordinates do not work for custom projections
=> Add projections to ApplicationMixin

.github/workflows/on-pull-request.yml, README.md, karma.conf.js, package.json
Adds coveralls reporting to the project
=> Add test coverage reporting

.github/workflows/on-push-master.yml, azure-pipelines.yml, jsduck.json, package.json
- Adds test JSDuck docs
- Disables (slow) Azure Pipelines builds in favour of GitHub workflow
- Publishes test site to gh-pages
- Adds coveralls
=> Add merge workflow for building app and docs

app/field/Feature.js, app/field/Line.js, app/field/Point.js, app/field/Polygon.js, app/model/FeatureStoreMixin.js, package.json, test/spec/field/Feature.spec.js, test/spec/field/Line.spec.js, test/spec/field/Point.spec.js, test/spec/field/Polygon.spec.js
Adds tests for all of the custom geometry fields - `CpsiMapview.field.*`
Docs updated and an unused property also removed.
=> Add feature field tests

app/form/RightInfoField.js, azure-pipelines.yml, test/load-tests.js, test/spec/form/ControllerMixin.spec.js, test/spec/form/RightInfoField.spec.js, test/spec/form/ViewMixin.spec.js, test/spec/form/ViewModelMixin.spec.js
=> Add Form mixin tests

app/controller/button/LoginButtonController.js, app/controller/form/Login.js, app/model/button/LoginButton.js, app/view/button/LoginButton.js, app/view/toolbar/MapFooter.js, test/spec/controller/button/LoginButtonController.spec.js, test/spec/view/button/LoginButton.spec.js, test/spec/view/form/Login.spec.js, test/spec/view/toolbar/MapFooter.js
This allows users to login and logout, and also displays their username and available permissions.
=> Create Login button

app/controller/LayerTreeController.js, app/controller/form/Login.js, app/model/FeatureStoreMixin.js, app/view/grid/ExampleGrid.js, app/view/grid/GridFiltersExample.js
- Set width of toast so all text is displayed
- Avoid double auto login (this is also called in `CpsiMapview.util.ApplicationMixin` `doLogin`
=> Login and requires fixes

app/controller/button/DigitizeButtonController.js, test/spec/controller/button/DigitizeButtonController.spec.js
Replace the current Message Box (as missing  features is more of a warning than error).
Tests also included (to run the code rather than check values).
=> Use toast for Digitizing tool missing features

app.js, app.json, app/Application.js, app/controller/toolbar/MapTools.js, app/util/ApplicationMixin.js, app/view/main/Main.js, app/view/toolbar/MapFooter.js, app/view/toolbar/MapTools.js, test/load-tests.js, test/spec/controller/toolbar/MapTools.spec.js, test/spec/util/ApplicationMixin.spec.js, test/spec/view/LayerTree.spec.js
This pull moves various common functions from individual applications to `CpsiMapview.util.ApplicationMixin` and `CpsiMapview.controller.toolbar.MapTools`
- add tests for `CpsiMapview.util.ApplicationMixin`
- add tests for `CpsiMapview.controller.toolbar.MapTools`
- update Google API
=> Move common functions to ApplicationMixin and MapTools

README.md, resources/data/layers/tree.json
Remove demo deployment notes as this is now done automatically as part of CI.
Also remove an unused layer from tree.json
=> ReadMe Update

app/form/ControllerMixin.js, app/form/ViewMixin.js
This PR adds a simple "close" button to the form mixin.
=> Close button

README.md, app/controller/button/FeatureSelectionButtonController.js, app/controller/grid/Grid.js, app/factory/Layer.js, app/model/grid/Grid.js, app/util/Layer.js, app/util/SwitchLayer.js, app/view/grid/ExampleGrid.js, app/view/grid/Grid.js, package.json, resources/data/layers/default.json, resources/data/styling/ruins.xml, test/spec/util/Layer.js
This pull request makes updates required to integrate the `CpsiMapview.controller.button.FeatureSelectionButton` into the PL application. 
Main changes include:
- Update to use a separate layer for selecting features which is not filtered along with the grid (or each selection will remove all features from the selection grid)
- Use a button group as the segmentedButton does not allow the toggleGroup to be set so each selection triggered lots of other map events
- Move the creation of WFS filters to the layer util function and avoid very similar code for both CpsiMapview.factory.Layer and CpsiMapview.controller.grid.Grid
- Add tests, and minor changes to the demo layers and grid
**Note** checks currently failing as the Coveralls site seems to be down.
=> Feature selection tool updates

app/form/ControllerMixin.js
Allows a hook other classes can use to add custom functionality.
=> Fire a deletesucceeded event

app/controller/toolbar/MinimizedWindows.js, app/controller/window/MinimizableWindow.js, app/form/LayersMixin.js, app/view/toolbar/MinimizedWindows.js, app/view/window/MinimizableWindow.js
Makes it easier to hook into when windows are hidden, closed, or minimized.
=> Updates to window and layer visibility handling

app/store/WfsFeatures.js
Allows for longer attribute filters.
=> Default grid requests to POST

app/controller/toolbar/MapTools.js
Ensures buttons/menus are correct when logging in with a different user
=> Listen to logout event

karma.conf.js, package.json
Hopefully fixes coverage issue
=> Update npm dependencies

app/view/LayerTree.js, resources/data/layers/default.json
=> Add missing requires and update help URLs

app/field/Feature.js, app/form/ControllerMixin.js
- Clear features before adding new ones
- check if a Window is destroyed before removing a mask
=> Minor fixes

app/controller/button/DrawingButtonController.js, app/controller/button/TracingMixin.js, app/util/Tracing.js, app/view/snappingExample/EdgeWindow.js, resources/data/layers/default.json
- references #560 
- This PR adds the attempt to also include edges that touch each other at the interior points.
=> Tracing Add-On: Support edges touching at interior points

app/controller/MapController.js
This PR allows `clickableLayerConfigs` accept both plain objects and a function which returns a config object.  The function receives the clicked feature as an argument which can be then used in custom logic. E.g. check a property on the feature and open the relevant edit window. The function returns an Id instead of keyField which allows for pre-processing of the Id before it is used by the model load function.
```javascript
{
layerKeyName: function (feat) {
return {
id: Math.abs(feat.get('ObjectId')), // the unique feature Id to open in a form
modelClass: 'CpsiMapview.model.ModelName', // the name of the class used to load a model
editWindowClass: 'CpsiMapview.view.EditWindow' // the name of the form view class to open when clicking on a feature
}
}
}
```
=> Allow custom logic in clickableLayerConfigs

package.json
Or get the following build errors:
```
[ERR] loading page file:///home/runner/work/cpsi-mapview/cpsi-mapview/sencha-cmd/ant/build/slicer/theme.html?_baseDir=%2Fhome%2Frunner%2Fwork%2Fcpsi-mapview%2Fcpsi-mapview%2Fbuild%2Ftemp%2Fproduction%2FCpsiMapview%2Fslicer-temp
setting base href to : file:///home/runner/work/cpsi-mapview/cpsi-mapview/build/temp/production/CpsiMapview/slicer-temp/
== Unhandled Error ==
ReferenceError: Can'''t find variable: Map
```
=> Pin the exact OL version

app/plugin/FeatureInfoWindow.js
Add a template function to cancel GetFeatureInfo requests to layers that may not support queries. These can be ignored currently when using `layer.get('featureInfoWindow')`, but this approach does not work when multiple WMS layers are combined in a single layer.
Example of usage:
```
plugins: [
{
ptype: 'cmv_feature_info_window',
percentageHeight: 0.5,
onBeforeRequest: function (layer) {
// return false to prevent a particular request
return layer.getSource().getParams().LAYERS.toLowerCase() !== 'clusterlayer';
}
}
],
```
In addition:
1. Log any responses from the server which are not in the expected GeoJSON format - MapServer may return errors in XML strings. 
2. Allow `percentageHeight` to be set to control the size of the window.
=> Control GetFeatureInfoRequests and log errors

README.md, app.json
Ensure the JS files are not compressed which breaks the demo builds
=> Fix build references

app/controller/grid/Grid.js, app/view/grid/Grid.js, test/spec/controller/grid/Grid.spec.js
- Order the items in column selection menu in the data grid alphabetically
- Added a test
=> Order column selection dropdown alphabetically, add test

karma-conf.common.js, package.json
Updates BasiGX path in karma-conf, bumps package.json version
=> Update BasiGX path in karma-conf

app/controller/addWms/AddWmsFormController.js, app/controller/button/DrawingButtonController.js, app/controller/button/FeatureSelectionButtonController.js, app/controller/button/SpatialQueryButtonController.js, app/controller/button/StreetViewTool.js, app/controller/button/TracingMixin.js, app/controller/panel/NumericAttributeSlider.js, app/model/FeatureEventsMixin.js, app/view/grid/Grid.js
Update the requires for BasiGX in app source files
=> Add missing BasiGX requires

app/controller/grid/Grid.js, app/view/grid/Grid.js
Follow-up pull request to #679.
=> Add Clear button to advanced Spatial Filter

README.md, app/form/ViewMixin.js, sass/src/view/LayerTree.scss
Fix padlock and filtering styling
=> Minor updates following testing

.github/workflows/on-push-master.yml
See https://stackoverflow.com/questions/73004195/phantomjs-wont-install-autoconfiguration-error
=> Disable SSL

package-lock.json, package.json
This includes the fix at https://github.com/terrestris/BasiGX/pull/754
=> Switch to using BasiGX from Compass GitHub
