compassinformatics/cpsi-mapview

app/factory/Layer.js
Use came-case function names for all functions in `LayerFactory`.
=> Harmonize function names in LayerFactory

app/view/LayerTree.js, app/view/main/Map.js
Use `Ext.GlobalEvents` for component-independent (global) event handling instead of letting the root-application managing this.
Background is the missing application-object, when `CpsiMapview` is used as library.
=> Use Ext.GlobalEvents for component-independent events

app/view/main/Map.js
This adds a `singleclick` handler on the map which fires an event `cmv-mapclick` with all clicked vector features and their corresponding layers.
The event propagates the clicked features and their corresponding layers, like 
`[{feature: aFeat, layer: layerOfFeat}, ...]`
and the original OpenLayers event. 
In order to react on the map click in an application, as in #28, just use the following code skeleton:
```javascript
var mapPanel = CpsiMapview.view.main.Map.guess();
mapPanel.on('cmv-mapclick',  function(clickedObjs, evt) {
// do sth. with the features here
console.log(clickedObjs, evt);
});
```
=>  Add 'singleclick' handler to MapPanel

app/factory/Layer.js, resources/data/layers/default.json
This adds a function to create an OGC WFS layer from the corresponding JSON configuration. So far no custom styling of features is implemented.
See #10.
=> Implement 'createWfs' function in LayerFactory (wo/ styling)

.gitignore, app/controller/button/MeasureButton.js, app/model/button/MeasureButton.js, app/view/main/Map.js, sass/src/view/main/Map.scss
This PR adds BasiGX measure tools to to header toolbar of cpsi-mapview.
Currently the following (Font Awesome) icons are used for buttons:
=> Measure tools

app/view/main/Map.js, app/view/toolbar/MapFooter.js
This adds a very basic map footer component which holds a resolution combo for now.
This combo shows an odd behaviour on first rendering, the prefix `1 :` is missing, upon zoom changes in the map it updates fine and displays correctly. I'll open a ticket for this, and think this shouldn't block this from being merged.
Fixes #17
=> Add a mapfooter skeleton

app/factory/Layer.js, app/view/layer/ToolTip.js, app/view/main/Map.js, resources/data/layers/default.json
This adds custom tooltips for hovered vector features on the map. The tooltips can be enabled if the corresponding layer has the property `tooltipsConfig` in its JSON-configuration:
Closes #27.
=>  Custom Tooltips for Vector Layers

app/view/main/Map.js
This includes a zoom in and out button, that both react on a single click and either zoom in or out.
See #18. 
@geographika Is this what was envisioned in #18?
We opted out of rectangle zoom-in and out AFAICT
=> Include zoom buttons

app/factory/Layer.js, app/view/toolbar/MapFooter.js
This uses the new BasiGX component `MapLoadingStatusBar` where 99% of the logic lives.
Depends on https://github.com/terrestris/BasiGX/pull/349
Please review.
Fixes #15
=> Show a progress bar when map sources load

app/view/main/Map.js
This records the state for map's zoom, center and rotation and adds it as hash to the current URL.
Inspired by http://openlayers.org/en/v4.6.5/examples/permalink.html
See #23.
=> Add map permalink functionality

app/controller/panel/TimeSlider.js, app/view/main/Map.js, app/view/panel/TimeSlider.js
This is a initial check in of the TimeSlider component (see #24). Currently, the following functionality is available:
* Update `ImageWMS` and `TileWMS` layers given in `layers array`, in particular parameter `TIME`
* Calculate the slider's increment, maxValue and minValue depending on selected time unit (currently year and month), the start time and the end time
* Pass a currently selected date to component
Open issues:
* Support WFS layers
* Support time ranges
=> Introduces timeslider component

app/factory/Layer.js
This PR suggests to implement virtual baselayers in a lean way, by just turning off other baselayers, when one baselayer becomes visible.
Fixes #16
=> Ensure maximum one virtual base layer is visible

app/factory/Layer.js, app/plugin/BasicTreeColumnLegends.js, app/view/LayerTree.js, app/view/main/Main.js, resources/data/layers/default.json, sass/src/view/LayerTree.scss
I went the very easy way instead of using the Legendtree of BasiGX, with which I had more trouble than expected.
Layers that have a `legendUrl` configured (with optional `legendWidth` and/or `legendHeight`) will have alegend underneath them. Future variants might use more logic to create legends on-the-fly for vector layer e.g. For this iteration we agreed on URLs as a minimal step.
Please review.
Fixes #26
=> Show legends underneath visible layer entries in the tree

app/factory/Layer.js
This adds two functions (`ol2PropsToOlLayerProps` and `ol2PropsToOlSourceProps`) to the `LayerFactory`, which transform the ol2-based properties of the JSON-configuration to ol4 pendants.
This cleans up the code and ensures all possible `"openLayers"` config properties are interpreted (where possible)
Related to #10
=> Map "openLayers" properties of JSON configuration 

app/controller/panel/TimeSlider.js, app/factory/Layer.js, app/view/main/Map.js, nginx.conf, resources/data/layers/default.json
This PR enabled time-dependent WFS layer by adding a filter to WFS request containing time interval.
In addition, a new property to define date format for each layer was introduces (closes issue #50)
This PR depends on https://github.com/meggsimum/cpsi-mapview/pull/49, which should be merged before.
=> Time range functionality for WFS layers

resources/data/layers/default.json
No functional change, just the default layer set is affected, especially usefull for the deployed application.
Will merge as soon as travis is fine.
=> Adjust default layers

app/model/button/MeasureButton.js, app/plugin/BasicTreeColumnLegends.js, app/view/LayerTree.js, app/view/toolbar/MapTools.js
This harmonizes the alias for `MeasureButton` ViewModel and the ptype for `BasicTreeColumnLegends`.
@geographika: If this gets merged the following has to be adapted as well: https://github.com/compassinformatics/publiclighting/blob/master/app/view/main/Map.js#L42 
Closes #61
=> Harmonize aliases 

app/factory/Layer.js, app/view/LayerTree.js, app/view/main/Main.js, app/view/main/Map.js, resources/data/layers/default.json
This introduces the possibility to group the layers in the `TreePanel` based on their `isBaseLayer` property / status. This behaviour can be activated by initializing the `CpsiMapview.view.LayerTree` with the config `structureMode: 'BASELAYER_OVERLAY'`. This results in two folders "Base Layers and Layers" in the Tree-Ui :
All other settings for `structureMode` will preserve the previous behaviour with a flat layer list.
This also ensures that the properties `qtip` and `iconCls` of the layer configuration get applied to modify tree layout and behaviour. 
Depends on https://github.com/geoext/geoext3/pull/453.
Closes #58.
=> Grouped layers as folders in LayerTree

app/view/LayerTree.js
Add filter function for `LayerTreeStore` to hide unwanted layers in tree. Flags to avoid a layer in the tree are `displayInLayerSwitcher=false` and `bp_displayInLayerSwitcher=false`.
Closes #46.
=> Filter function for LayerTreeStore

.sencha/app/production.properties
This avoids the compression of external JS resources (like `OpenLayers` or `GeoStylerSLDParser`) since they are already compressed and another compression leads to errors in the production build.
=> Avoid compression of external JS resources

app/controller/button/DigitizeButtonController.js, app/model/button/DigitizeButtonModel.js, app/view/button/DigitizeButton.js, app/view/toolbar/MapTools.js
This PR solves issues #73 and #74 by introducing a new class `DigitizeButton`.
For usage examples, see the MapTools.js, where 3 different kinds of buttons are used which should be sufficient for the different usecases like "Zone Tool" and "Network Solver Tool".
The last 2 methods in the controller can be removed as they currently only act as a showcase.
@chrismayer please review
=> Zone and Network Solver Tool

app/plugin/TreeColumnContextMenu.js
Adds a plugin in order to show a ContextMenu for a layer in the LayerTree.
This is done by overwriting / implementing the `GeoExt.plugin.layertreenode.ContextMenu`. Creates all  items configured in the `menuItems` config property. These have to be valid xtypes of a `Ext.menu.Item` or a derived component.
**CAUTION: This cannot be merged before https://github.com/geoext/geoext3/pull/501 is merged.**
=> ContextMenu plugin for a layer in the LayerTree

app/factory/Layer.js, app/plugin/TreeColumnContextMenu.js, app/view/LayerTree.js, app/view/menuitem/LayerRefresh.js
This adds a "Refresh Layer" tool as `MenuItem` in the `LayerTree`'s ContextMenu.
Closes #77
=> Add "Refresh Layer" tool as item in layer context menu

app/factory/Layer.js, app/view/LayerTree.js, app/view/menuitem/LayerLabels.js, app/view/menuitem/LayerRefresh.js
This adds a "Labels Layer" tool as `MenuItem` in the LayerTree's `ContextMenu`.
Currently contains the changes of #83 since this is based on that and is not merged yet. Please ignore the changes of #83. Main class to review is  `app/view/menuitem/LayerLabels.js`
Closes #78
=> Add "Labels Layer" tool as item in layer context menu 

app.json
This fixes the the failing sencha build by ignoring the `form` directory of `geoext3` in the classpath definition.
Please review and test with `Sencha Cmd 6.2` @annarieger.
=> Fix sencha build

app/factory/Layer.js
Merge possibly set additional filters coming from GeoExt FeatureGrid with other filters (e.g. bbox, time).
Depends on https://github.com/geoext/geoext3/pull/513
Addresses https://github.com/meggsimum/cpsi-mapview/issues/79#issuecomment-486648150
Please reivew @marcjansen @dnlkoch
=> Support additional filters for WFS

app.json, app/view/toolbar/MapTools.js
This PR adds two gazetteer components:
- a Nominatim based geocoding combobox from GeoExt
- a custom CPSI gazetteer / geocoding combobox (extending the `GeocoderCombo` of GeoExt)
Closes #70
=> Add gazetteer components

app/view/combo/Gazetteer.js
This adds the missing Gazetteer combo class (needed for the changes introduced with #89).
=> Add missing Gazetteer combo class

app/view/combo/Gazetteer.js, app/view/toolbar/MapTools.js
Avoids showing the result layers of the geocoding / gazetteer comboboxes in the LayerTree.
=> Do not show geocoding layers in LayerTree

app/controller/button/StreetViewTool.js
This PR ensures that the SV panorama is rendered to the body of the floating window. So the layout issue described in #71 gets fixed.
=> Render SV panorama to body of floating window

.eslintrc.js, app/controller/panel/NumericAttributeSlider.js, app/factory/Layer.js, app/view/panel/NumericAttributeSlider.js, app/view/toolbar/MapTools.js, resources/data/layers/default.json
This adds a new slider that controls a numerical filter which will be applied to associated layers.
Originally wanted:
>    A new slider class with range options – very similar to the TimeSlider class
>        https://github.com/meggsimum/cpsi-mapview/blob/master/app/controller/panel/TimeSlider.js
>        https://github.com/meggsimum/cpsi-mapview/blob/master/app/view/panel/TimeSlider.js
>    The component would allow multiple layers to be registered with it (allowing them to all be filtered by a range)
>    A property would be set on the slider to use as the filter field (this would be a numeric field)
>    When the slider is active (using a checkbox similar to the “Time range” above) a filter is applied to the registered layers
>    The filter would apply to WMS and WFS layers using the …
=> Add a numeric attribute slider

resources/data/layers/default.json
This corrects the URL of the ESRI REST World_Light_Gray_Base layer since the x-y-z declaration for the tiles has to be given in the config URL (introduced with #107).
=> Correct URL for ESRI REST World_Light_Gray_Base

package.json
This PR does 2 things:
- Introduce separate `lint` script (besides calling it in `test` script)
- Upgrade eslint to v6.2.1
First small preparation steps for #105
=> Introduce separate lint script and upgrade eslint 

app/controller/button/SpatialQueryButton.js
When testing the new SpatialQueryButtonController in #116 I was getting errors that `view.map is null` on the `view.map.addInteraction(me.drawQueryInteraction);` line. 
Also the code was getting a map rather than a mapComponent with:
`var mapComp = CpsiMapview.view.main.Map.guess();`
This switches it to:
`var mapComp = me.mapComponent || BasiGX.util.Map.getMapComponent();`
If not `mapComp.getMap()` is `undefined. 
Several other tools use the same approach e.g. the [DigitizeButtonController](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/button/DigitizeButtonController.js)
@ahennr - could you check the changes to see that they make sense?
Thanks for all the work on the tool!
=> Switch to getting mapComponent

app/plugin/TreeColumnInResolutionRange.js, app/view/LayerTree.js, resources/data/layers/default.json, sass/src/view/LayerTree.scss
This PR adds a new plugin `TreeColumnInResolutionRange` that changes opacity and font style of a layer tree node if the assigned layer is not in range. In addition, the visible scales are shown in a qtip if tree node is hovered.  
Depends on https://github.com/geoext/geoext3/pull/580, as soon as this is merged, I'll remove WIP state
=> Layer tree - Update tree nodes depending on layers resolution restrictions

app/factory/Layer.js, resources/data/layers/default.json
Add a GUID that can be used to find a lyaer. 
This is to avoid events etc. breaking when relying on text labels to find layers, and forgetting to update whenever a label changes.
=> Add a new layer GUID property

app/controller/button/SpatialQueryButton.js
Trigger a new custom event containing the spatial filter created by the tool. This can then be combined with other filters external to the tool to make complex filters. 
The current functionality is preserved by default, but can be deactivated by setting the triggerWfsRequest flag to false in cases where the button should simply create a filter and fire the event.
=> Fire an event with the spatial Ext.util.Filter

app/factory/Layer.js
This pull request moves the WFS filtering to a separate function, which allows it to be called by the Vector Tiles via WMS facade and add the filter to the loader function. 
Only drawback could be performance? Filters have to be recreated on each request. Test speeds in the prototype system seem fine.
=> Allow filtering of vector tiles through WMS facade

app/factory/Layer.js, app/view/main/Map.js, resources/data/layers/default.json
Hey there!
I created a [switch layer](https://github.com/compassinformatics/cpsi-mapview/issues/103) type in the layer factory. 
It adds a listener on the resolution: when the resolution changes all layers are checked if they are switch layers and if they need to be switched. After a switch the layertree gets updated.
=> Add switch layer functionality

.eslintrc.js, app/plugin/BasicTreeColumnLegends.js, app/plugin/TreeColumnStyleSwitcher.js, app/view/LayerTree.js, app/view/layer/StyleSwitcherRadioGroup.js, resources/data/layers/default.json
This ensures that the legend for WMS / WFS is shown by `getLegendGraphic` request (if not defined as static image) and that the legend will be updated in case the layer style is changed by the user.
Convention to activate the automatic `getLegendGraphic` is that either `legendWidth` or `legendHeight` has to be defined in the WMS / WFS layer confinguration and no property `legendUrl` is set.
For WFS the WMS `getLegendGraphic` request is used by convetion, as specified in #117.
=> Switch layer legend with style

app/plugin/BasicTreeColumnLegends.js, app/util/Legend.js, app/view/layer/StyleSwitcherRadioGroup.js, resources/data/layers/default.json
This pull request also removes the need to set legend widths and heights for autolegends on WMS layers.
=> Allow style switching for MVT layers

app/util/Legend.js
Allow legends to be generated without an explicit STYLE (using the default).
This pull request also fixes URLs for MapServer which often end with an ampersand e.g. mapserv?map=/path/my.map&
=> Autolegend Generation Fixes 

app/factory/Layer.js, app/view/LayerTree.js, app/view/menuitem/LayerOpacity.js, resources/data/layers/default.json
This adds a layer opacity slider context menu for all layers in the tree (see #146). 
Add `opacitySlider: false` in the layer configuration to avoid the layer opacity slider.
NOTE: Since using `setOpacity` for `ol.layer.VectorTile` instances has no effect, this introduces a workaround by changing `globalAlpha` in `precompose` of the layer.
See openlayers/openlayers#4758
=> Add layer opacity slider context menu 

.eslintrc.js, README.md, app/controller/form/Login.js, app/view/form/Login.js, app/view/toolbar/MapFooter.js, karma.conf.js, package.json, test/resources/data/forms/login.json, test/spec/view/form/Login.spec.js
Adds a login form that can connect to an authentication service and save a token to a cookie.
Tests also added. 
As development is done on Windows machines I've turned off Unix line break checks for now.
=> Add a Login form

app/controller/button/DigitizeButtonController.js
the error message wasn't actually displayed because of the missing brackets
=> bug in error message display fixed

app/plugin/TreeColumnStyleSwitcher.js, test/spec/view/LayerTree.spec.js, test/spec/view/layer/StyleSwitcherRadioGroup.spec.js, test/spec/view/plugin/TreeColumnStyleSwitcher.spec.js
This ensures that the style radio groups in the LayerTree are rendered after a node has been dragged and dropped. Otherwise they disappear.
Fixes #169
=> Fix disappearing style radios when moving layer

app/controller/grid/Grid.js, app/view/grid/Grid.js
Only return data for visible columns using WFS propertyName using new propertyName property on the GeoExt WFS store.
=> Only return data for visible columns using WFS propertyName

app/plugin/TreeColumnStyleSwitcher.js, app/view/LayerTree.js, resources/data/layers/default.json, resources/data/layers/tree.json
This adds a general mechanism for a grouped `LayerTree`, which is based on a JSON tree structure (see resources/data/layers/tree.json) which defines folders and leafs for the `LayerTree`. The corresponding layers are referenced by the property `layerkey`, so the current layer creation (and thus the layer JSON) can stay untouched.
Here is an example for a tree.json
```json
{
"id": "root",
"children": [
{
"id": "overlay-folder",
"title": "Layers",
"children": [
{
"id": "LIGHT_UNIT_MVT",
"isLeaf": true
},
{
"id": "ACCIDENTS_WFS",
"isLeaf": true
},
{
"id": "GAS_WFS",
"isLeaf": true
}
]
},
{
"id": "base-folder",
"title": "Base Layers",
"children": [
{
"id": "OSM_BACKGROUND",
"isLeaf": true
},
{
"id": "GREY_BACKGROUND",
"isLeaf": true
}
]
}
]
}
```
Closes #145
=> General mechanism for grouped LayerTree

app/view/toolbar/MapFooter.js
This sets a different initial EPSG code for the mouse position UI (`basigx-panel-coordinatemouseposition`).
Therefore the BasiGX submodule has been updated to the current master (8c8a1d).
Closes #160
=> Set different initial EPSG code for mouse position

app/controller/window/MinimizableWindow.js
@jansule - relates to comment in #179 
The toolbar should be there for derived applications, but this check means it can be easily tested without if required.
=> Add guard against missing toolbar

resources/data/layers/default.json
This removes the Vector Tile layer `LIGHT_UNIT_VT` since the service backend is not available anymore. The layer is usable via VT WMS protocol, see layer `LIGHT_UNIT_MVT` (as suggested by @geographika in #186).
=> Remove unavailable VT layer

app/controller/button/SpatialQueryButton.js, app/controller/grid/Grid.js, app/view/button/SpatialQueryButton.js, app/view/grid/Grid.js, app/view/menuitem/LayerGrid.js
Adds the option `displayPermanently` to the `CpsiMapview.view.button.SpatialQueryButton` Component.
If true, a layer will be added that holds the geometry for the spatial query. This layer will remain visible unless the window which holds the LayerGrid will be closed and/or the visibility of the layer to query changes.
**Important:** In order to properly connect to the layer to query, the `layerKey` property of the layer has to be added via `vectorLayerKey` as additional property to the `SpatialQueryButton`.
The `SpatialQueryButton` now has additional static methods for handling the visibility and clearing of a geometry. These functions require the `ol.map` as well as the `layerKey` property of the layer to query. This allows handling the visibility and clearing of the layer from anywhere …
=> Add option to display spatial filter polygon

app/view/LayerTree.js, sass/src/view/LayerTree.scss
BaseLayers will now be displayed with radio buttons instead of checkboxes. Uses property `isBaseLayer` for distinguishing baseLayers from overlays.
fixes #143
=> Display baselayers with radio buttons

app/factory/Layer.js
Likely an issue in MapServer, but handle in JS for now by checking for an empty string. 
MapServer issue for reference:
Request:
```xml
/mapserver/?map=/MapServer/apps/mapview-demo/example.map&&SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application/json&TYPENAME=Boreholes&SRSNAME=EPSG:3857&FILTER=<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:And><ogc:PropertyIsGreaterThanOrEqualTo><ogc:PropertyName>YEAR</ogc:PropertyName><ogc:Literal>1951</ogc:Literal></ogc:PropertyIsGreaterThanOrEqualTo><ogc:PropertyIsLessThanOrEqualTo><ogc:PropertyName>YEAR</ogc:PropertyName><ogc:Literal>1983</ogc:Literal></ogc:PropertyIsLessThanOrEqualTo><ogc:BBOX><ogc:PropertyName>msGeometry</ogc:PropertyName><gml:Envelope xmlns:gml="http://www.opengis.net/gml" …
```
=> Check WFS response is not empty

app/factory/Layer.js
Use Ext.Object.merge in case the openLayers object does not yet exist
=> Fix error when openLayers object not set on switchLayer

app/view/main/Map.js
Before the content of sub-objects in the default settings
were not applied to the layer config if the same sub-object
(also with different properties) already existed. This
commit fixes this issue by replacing the `apply` function
with the `merge` function.
=> Add recursive defaults

app/view/grid/ExampleGrid.js, app/view/toolbar/MapTools.js, package.json, resources/data/layers/default.json, resources/data/layers/tree.json, resources/data/styling/Waterbodies_Default.xml, resources/data/styling/Waterbodies_Type.xml, resources/data/styling/ruins.xml
A new standalone project has been created at https://github.com/compassinformatics/mapview-demo and running at http://w08-mapserver.compass.ie/mapserver/?map=\MapServer\apps\mapview-demo\example.map& to serve layers for the cpsi-mapview project. 
These demo layers will not be subject to changes, unlike several WMS and WFS services currently used in the project. 
Broken layers have been removed and replaced with new layers, while retaining the functionality in the demo. 
Should address #183 and #173
=> Use new layers from demo project

app.json, azure-pipelines.yml
This pull request cleans up the Azure Pipeline with additional comments. 
The app.json was also breaking the SenchaCmd build process for unknown reasons. The error was:
```
setting base href to : file:///D:/GitHub/cpsi-mapview/build/temp/production/CpsiMapview/slicer-temp/
== Unhandled Error ==
TypeError: No default value
https://maps.googleapis.com/maps/api/js?v=3.36&key=INSERT_YOUR_API_KEY_HERE:27 in Ba
https://maps.googleapis.com/maps/api/js?v=3.36&key=INSERT_YOUR_API_KEY_HERE:27 in value
file:///D:/GitHub/cpsi-mapview/node_modules/geostyler-sld-parser/browser/sldStyleParser.js:1 in exports
```
The file ``cpsi-mapview\build\temp\production\CpsiMapview\slicer-temp\bootstrap.json`` contained the following:
```json
{"remote":true,"path":"https://maps.googleapis.com/maps/api/js?v\u003d3.36\ …
```
=> Fix SenchaCmd Build in Azure Pipeline

app/view/main/Map.js, app/view/toolbar/MinimizedWindows.js, sass/src/view/main/Main.scss
This is a follow up of #179 
The minimizedWindows toolbar is now transparent and was positioned over the map.
=> Set minimizedWindows transparent & position it over map

app/view/window/MinimizableWindow.js
By default all `cmv_minimizable_window`s should be constrained
=> Constrain cmv_minimizable_window to Viewport

app/controller/button/StreetViewTool.js
If the tool is toggled before the window is created a JS error is thrown
=> Fix StreetView toggling

app/controller/grid/Grid.js, app/view/grid/Grid.js
The WFS server only returns data for displayed columns. If new columns are made visible they currently appear empty until a refresh. 
This pull request makes a new server request each time a new column is displayed.
=> Reload grid if new columns are added

app/controller/toolbar/MinimizedWindows.js
The line `var button = me.getView().items.find(function (item) {` was throwing a `items find is not a function` error. 
The function is deprecated for a [Ext.util.ItemCollection](https://docs.sencha.com/extjs/6.2.0/modern/Ext.util.ItemCollection.html#method-find)
The worst thing was the code runs fine locally in dev with the exact same framework, but would fail in the minified production code. 
Replacing with `findBy`. 
Note `find` is used in other places in the codebase but is fine for a [Store](https://docs.sencha.com/extjs/6.2.0/modern/Ext.data.AbstractStore.html#method-find), [Ext.util.Collection](https://docs.sencha.com/extjs/6.2.0/classic/Ext.util.Collection.html#method-find), and standard JS [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Arr …
=> Replace find with findBy

app/factory/Layer.js
This pull request allows any WMS options and custom parameters to be sent to the server when set in the layers config JSON file. 
Parameters are all uppercases to avoid duplicates, and a warning is logged if no LAYERS parameter is set.
=> Allow any serverOptions to bet set on a WMS

app/view/button/DigitizeButton.js, app/view/toolbar/MapTools.js
Only trigger the showcase DigitizeButtonController onResponseFeatures in the sample mapview application
This avoids having to remove the function, or sublass the button in other applications.
=> Netsolver default handler

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js
This update allows a `resetOnToggle` option to be set on `cmv_digitize_button` that can when `true` (the default) clears the resultLayer when the tool is deactivated, and leaves the features and polygon displayed in the layers when set to `false`. 
This allows a grid to be bound to the resultsLayer without clearing features when the tool is deactivated.
=> Add toggle option for resetting results

app/controller/grid/Grid.js, app/view/grid/Grid.js
A generic double click handler that will create a new "detailed" model based on the selected row in the grid. 
This relies on 2 properties being set in the grid ViewModel:
```
associatedEditModel: 'ProjectName.model.ChildModelName',
associatedEditWindow: 'ProjectName.view.child.WindowName',
```
If either or these have not been set the handler will do nothing. 
It is recommended to add the model and window classes as requires to the grid's ViewModel where they are referenced.
=> Add default rowdblclick handler to the grid to open an associated form

app/controller/button/DigitizeButtonController.js
This allows more flexibility so the `resultLayer` can be created and added independently of toggling the tool.
=> Only add tool generated layer to the map

app/view/window/MinimizableWindow.js
The [Resizer](https://docs.sencha.com/extjs/6.2.0/classic/Ext.resizer.Resizer.html) on a Window blocks clicking on the Close button in the top-right of the grid window (whilst not blocking it completely it makes it difficult to click on). 
This pull request removes the handlers from the right of the Window. 
The handlers can also be reduced from 10px by setting the SASS variable: `$resizer-handle-size: dynamic(5px);` however this only reduced the annoyance slightly.
=> Remove handler from right-hand side of Windows

app/controller/button/DigitizeButtonController.js, app/controller/toolbar/CircleSelectionToolbar.js, app/view/toolbar/CircleSelectionToolbar.js
Add an Enter key shortcut to pressing the Apply button.
Also look throughout the entire application for a default parent container (to allow the button control to be added to a floating window rather than a map toolbar). 
Add missing requires.
=> Allow Enter key to get Circle results

app/view/grid/Grid.js
To avoid expanding off screen when paging is turned off.
Subclasses can override this.
=> Fix grid size

app/view/grid/Grid.js, app/view/menuitem/LayerGrid.js
When creating new grid windows use a flex layout to fill all available space
=> Remove fixed grids height and use a flex fit layout instead

app/view/LayerTree.js
This pull request waits until the map layers have been added to the map before applying the tree structure. 
This allows the structure to work correctly in older version of the Edge browser. It does however rely on the `cmv-init-layersadded` event being called and so does not allow a local configuration. 
In addition this pull request renames "Root" to "root" as this name is used [here in the TreeColumnStyleSwitcher](https://github.com/compassinformatics/cpsi-mapview/blob/7cb03dbf484582e10f9ee5cd718e56b2862c8bbe/app/plugin/TreeColumnStyleSwitcher.js#L145) and is case-sensitive.
=> Apply tree structure after all layers are loaded. See #241

resources/data/layers/default.json
See #214 - it looks like the backend service is may not be configured for WFS 2.0.0
I've switched to 1.1.0 and the layer now displays, and the vector lables added for #144 now work correctly. 
I also hardcoded a legendUrl. Other WFS layers use MapServer WMS styles which mirror a WFS but this may not be the case for the GAS WFS which is hosted on GeoServer.
=> Fix Gas WFS version and hardcode image

app/factory/Layer.js, app/view/layer/StyleSwitcherRadioGroup.js, app/view/menuitem/LayerLabels.js
Some issues arose with SLDs with multiple filters e.g. 
```js
["&&", Array(3), Array(3)]
// [">=", "Height", "0 "]
// ["<", "Height", "7 "]
```
These would throw the following error:
```
Error:   var filterVal = rule.filter[2];
Layer.js?_dc=1586508526324:910 Uncaught (in promise) TypeError: Cannot read property '2' of undefined
at Object.<anonymous> (Layer.js?_dc=1586508526324:910)
at Object.each (Array.js?_dc=1586508526323:379)
at constructor.forceNumericFilterValues (Layer.js?_dc=1586508526324:909)
at Layer.js?_dc=1586508526324:843 
```
Initially I attempted to update this function to handle all filter types (see JS at end of the issue). However when debugging it appeared this was duplicating code in the geostyler-openlayers-parser library, and on further investigation the library also …
=> Remove stylesForceNumericFilterVals

.eslintrc.js, app/controller/panel/TimeSlider.js, app/factory/Layer.js, app/field/Feature.js, app/field/Line.js, app/field/Polygon.js, app/model/FeatureEventsMixin.js, app/model/FeatureStoreMixin.js
This pull request contains several classes that provide links between ExtJS data models and GeoExt feature stores / OpenLayers layers. 
Several application models have fields which store references to collections of features. For example an "edges" property could store a collection of line features relevant to a road survey. 
These fields are populated by JSON, and using the new `CpsiMapview.model.FeatureStoreMixin` automatically have a feature store created for them, a layer added to the map, and the model-store-layer kept in sync. 
Custom fields are also available to serialize OL features back to either simplified JSON arrays or GeoJSON to send back to the server as part of a PUT request. The fields also allow customisation of map layer styling using field properties. 
Finally the …
=> Add Model-Feature Linking Classes

app/controller/form/Login.js, app/controller/grid/Grid.js
When using init sometimes the this.getViewModel() returned `null`.
=> Use initViewModel to avoid getViewModel null errors

app/plugin/TreeColumnStyleSwitcher.js
Use refresh rather than itemupdate as the radiobuttons created by CpsiMapview.plugin.TreeColumnStyleSwitcher were disappearing when layers were shown or hidden. 
To recreate the issue - a layer was hidden using `layer.setVisible(show);`
This triggered a call to `doRefreshView` for the treeview. However at the end `view.refreshNeeded === false` and the `itemupdate` event wasn't triggered. Swtiching to the `refresh` event fixed the issue.
=> Fix disappearing style radio buttons

app/util/ApplicationMixin.js
With direct `Ext.Ajax` requests the `response` object did not have a `responseType` (as it had not been passed through a reader). 
This change checks the raw HTTP response headers  and if necessary parses the raw text into JSON.
=> Parse JSON from a server without a reader

app/controller/form/Login.js, app/util/ApplicationMixin.js, app/view/form/Login.js
Fix use case when automatic login destroys view and then tries to show automatically. This caused various viewmodel calls when the form had been destroyed (causing JS errors). 
Now the ApplicationMixin keeps a reference to the form and shows it when necessary.
=> Fix login bug with expired token and destroyed viewmodel

app/model/FeatureStoreMixin.js
FeatureStores need to be created `before` the constructor, if not a field's `convert` function is run but no store is ready to load the data at https://github.com/compassinformatics/cpsi-mapview/blob/42feb14be813afc543f5bb72330d559f178d5090/app/field/Feature.js#L25
=> Create featureStores before model constructor in CpsiMapview.model.FeatureStoreMixin

app/field/Feature.js
Previously a GeoJSON object was saved by the reader, and the OL feature arrays when using the network tools. This led to issues with field validators checking different object types. This pull request ensures it will always be an array of OL features or null.
=> Set CpsiMapview.field.Feature to use an array of OL features

app/controller/grid/Grid.js, app/factory/Layer.js, app/util/WmsFilter.js, app/view/menuitem/LayerLabels.js
Adds in  a util class for working with WMS filters. These are a vendor-specific parameter for WMS supported by MapServer under https://mapserver.org/development/rfc/ms-rfc-118.html
It also relies on https://github.com/MapServer/MapServer/pull/6139 to correctly implement duplicated layer names in a WMS request with filters.
The util class is used in all classes what create WMS requests - the layer labels plugin, the grid, and the layer factory for switch layers. 
A performance improvement is added to the layer labels to prevent duplicate WMS requests when the filter has not changed.
=> Add new util class to handle WMS filter creation

app/field/Feature.js, app/model/FeatureStoreMixin.js
Add edit session when loading features from GeoJSON for the first time, prior to edits, and then check to see if the model is being edited to avoid setting the dirty flag.
=> Ensure model is not set to dirty when first loaded

app/controller/LayerTreeController.js, app/view/LayerTree.js
This PR moves code from the LayerTree view into a new LayerTreeController as it belongs from a MVC point of view into a controller.
It also extracts code from `updateLayerNodeUi` into a new function `getNodeForLayer`.
=> Refactored LayerTree to LayerTreeController

app/view/window/MinimizableWindow.js
Only restrict header to viewport by default rather than the full window
=> Use constrainHeader for MinimizableWindow

app/controller/LayerTreeController.js, app/data/model/LayerTreeNode.js, app/factory/Layer.js, resources/data/layers/default.json, resources/data/layers/tree.json, sass/src/view/LayerTree.scss
This PR moves tree UI related configurations options, such as `'text'`, `'qtip'` or `'iconCls'` to the tree JSON file (`tree.json`).
**Caution**: Merging this needs adaption of existing configuration files for apps based on CPSI-MapView:
- `'text'`, `'qtip'` or `'iconCls'` fields have to be moved to the tree.json file
- `'isLeaf'` property in tree.json is now `'leaf'` ('isLeaf' accepted for legacy reasons) 
- folders in tree.json need an `'expanded'` property set to true in case they should be expanded on startup 
See resources/data/layers/tree.json as a working example.
=> Move tree related configs to tree.json

app/controller/LayerTreeController.js, resources/data/layers/tree.json
This allows to define a section `"defaults"` > `"general"` having default values for tree node configurations, so duplication of properties can be avoided.
CAUTION: The general structure of tree.json is changed with this PR and needs adaption in existing applications:
before:
```json
{
"id": "root",
"children": [
{
"id": "overlay-folder",
...
```
after:
```json
{
"defaults": {
"general": {}
},
"treeConfig": {
"id": "root",
"children": [
{
"id": "overlay-folder",
...
```
Resolves #291
=> Apply default values for tree nodes

app/factory/Layer.js, app/plugin/FeatureAttributeGrouping.js, app/view/main/Map.js
This is implemented reacting to the hover event and has only a very basic styling option (color).
This is maybe a good point to get some feedback @geographika
Configuration is done in the `default.json` in the layer object like this:
```
"grouping": {
"attribute": "some-attribute",
"color": "green"
}
```
Starting this grouping on hovering has two disadvantages, though:
* the highlight is removed when the mouse is moved or if implemented differently as soon as another feature is hovered.
* It can interfere with the get feature info (the picture below)
What styling options are needed apart from color?
It is to mention that this grouping would out of the box not work with clustered layers.
=> Feature Attribute Grouping Plugin

app/controller/LayerTreeController.js
@chrismayer - a couple of fixes required when integrating with larger application. 
1. Add missing requires. 
2. `isBaseLayer` code removed as can now be set in tree.json (old approach no longer works):
```
{
"id": "OSM_BACKGROUND",
"text": "OpenStreetMap",
"iconCls": "fa-map",
"cls": "cpsi-tree-node-baselayer"
},
```
=> Add missing requires and remove baselayer class code

app/controller/grid/Grid.js
This was referenced in the grid view but never implemented:
https://github.com/compassinformatics/cpsi-mapview/blob/3722bb3bd5cb3397816c4e4fba6ab5f4b596dd42/app/view/grid/Grid.js#L109
Removes any sorting on the WFSStore.
=> Add missing onClearSort function to grid controller

app/controller/LayerTreeController.js, app/view/LayerTree.js, app/view/addWms/AddWmsForm.js
This pull request has a few changes following integration into a large application. 
1. Makes the config for the Add WMS window cofigurable on the LayerTree view. As this is where the xtypes are set I also moved the requirements for the default `cmv_minimizable_window` and `cmv_add_wms_form` here. 
2. Adds a missing controller requires (JS errors otherwise) - `CpsiMapview.controller.addWms.AddWmsFormController`
Applications using the mapview library can then fully configure the Add WMS window from the LayerTree:
```js
addWmsWindowConfig: {
xtype: 'cmv_minimizable_window',
title: 'Add External Map Layer',
items: [{
xtype: 'cmv_add_wms_form',
width: 400,
wmsBaseUrls: [
'http://gis.epa.ie/geoserver/wms',
'https://ows.terrestris.de/osm/service',
]
}]
}
```
3. Makes the form hidden rather than …
=> Allow the Add WMS Window to be configured

resources/data/layers/tree.json
Adds `"cls": "cpsi-tree-node-baselayer"` to the tree configurations of the BaseLayers, so the application looks as before (follow-up for #294).
=> Add cls 'cpsi-tree-node-baselayer' to base layer tree configs

app/data/model/LayerTreeNode.js
This pull request avoids setting the `checked` property on a layer which is not visible in the layer tree - this avoids an unnecessary redraw of the tree. 
It also makes the `CpsiMapview.data.model.LayerTreeNode` use the `ol3` `__toggleMode` by default - avoiding keeping parent checkboxes and children in synch, but also avoiding redrawing nodes. 
*Unsure if this has a major performance impact*.
=> Avoid layer tree updates for layers not in tree

app/model/grid/Grid.js, app/view/grid/Grid.js
Adds a new configurable setting on the view model. Useful when using WFS grids without geometries.
=> Allow 'Select by Shape' button to be hidden

app/controller/window/MinimizableWindow.js, app/model/window/MinimizableWindow.js, app/util/ApplicationMixin.js, app/view/grid/ExampleGrid.js, app/view/menuitem/LayerGrid.js, app/view/window/MinimizableWindow.js
This pull request adds a Help tool to windows with a helpUrl set in their viewModel. 
For custom grids VM properties are applied to their auto-generated container windows.
=> Add a Help Icon to Windows

app/plugin/BasicTreeColumnLegends.js, app/util/Html.js, app/util/Legend.js, app/view/LayerTree.js
This caches the legend images as dataURLs in an internal lookup, so the images only have to be queried at the first activation of the legend graphic in the tree.
@geographika Could you please give it a try in an application with a large amount of layers in order to test if this brings a performance boost for the layer tree? TIA! 
Relates to #274
=> Cache legend images

app/plugin/BasicTreeColumnLegends.js
Relates to #284 - currently legends are cached per layer, but individual WMS STYLEs can have different legends. This pull request caches at the LAYER/STYLE level.
=> Cache legends based on layer plus STYLE

app/controller/grid/ItemDeleterGridControllerMixin.js, app/model/FeatureStoreMixin.js
Ensure features associated with a row record are removed from the layer as there is no 2-way binding - see https://github.com/geoext/geoext3/issues/636
Use `remove` rather than `erase` which is for server callbacks, and also causes strange errors in OpenLayers. 
Also some typo fixes in ItemDeleter.
=> Remove features from layer when records deleted from store

app/model/FeatureStoreMixin.js
Otherwise OL throws an error as the key is missing in `featureChangeKeys_`:
```js
removeFeatureInternal(feature) {
const featureKey = getUid(feature);
this.featureChangeKeys_[featureKey].forEach(unlistenByKey);
delete this.featureChangeKeys_[featureKey];
```
=> Fix to prevent features being removed twice

app/view/fileupload/FileGrid.js
In case the grid is included in a readonly form, add and remove buttons can easily be hidden via binding
=> FileGrid buttons binding improved (buttons can be hidden)

app/controller/button/DigitizeButtonController.js, app/field/Feature.js, app/field/Polygon.js
Only a single polygon should be used to select features. 
If multi-polygons are still created then add a warning and send the most recently created to the server. 
Some `DigitizeButtonController` typo updates while debugging multiple polygons.
=> Ensure only a single polygon is created and sent to server

app/plugin/BasicTreeColumnLegends.js
This fixes the legend detection and caching for different styles. Executes the caching only for layers with WMS-based sources (since other source types do not have a `getParams` function). Otherwise a lot of warnings show up in the developer console.
=> Fix "getLegendHtml" for different styles

app/controller/MapController.js, app/controller/button/DigitizeButtonController.js, app/factory/Layer.js, app/plugin/FeatureInfoWindow.js, app/view/main/Map.js, resources/data/layers/default.json
Resolves #251
This is still missing some documentation but can already be tested. It can be added as a plugin to the Map component:
```
plugins: [
{
ptype: 'cmv_feature_info_window'
}
],
```
Only layers will be queried, that have the property `featureInfoWindow` set to `true` in the `default.json`.
It looks like this:
=> WMS GetFeatureInfoWindow

app/controller/LayerTreeController.js, app/factory/Layer.js
This ensures that for an exchanged switch layer the correct text (layer name) will be shown in the tree node.
Follow-up for #289 as detected in #319.
=> Ensure tree node text is updated for switch layer

.eslintrc.js, app.json, app/factory/Layer.js, app/view/LayerTree.js, app/view/menuitem/LayerMetadata.js, resources/data/layers/default.json
resolves #240 
It shows the "Metadata" option for all layers, like specified in the description. 
However, metadata can only be retrieved for WMS and WFS layers from MapServer. 
Metadata for Vectortiles could also be possible, but the layername and the baseurl are difficult to extract, since they are not separetely added in the config file (like for WMS and WFS). Both layername and baseurl could of course be extracted from the connection-url:
`https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=waterways&TILED=false&CRS=EPSG%3A3857&WIDTH={width}&HEIGHT={height}&BBOX={bbox}&STYLES=Waterways&FORMAT=mvt`
However, it might be more elegant and consistent to provide the …
=> Add metadata plugin

app/data/model/LayerTreeNode.js, app/util/Style.js, app/view/LayerTree.js, app/view/layer/StyleSwitcherRadioGroup.js, app/view/menuitem/LayerStyleSwitcher.js, resources/data/layers/default.json
This makes the RadioGroup to switch between styles (normally rendered under the corresponding layer tree node) usable in the context menu of the tree node. By setting the config property `styleSwitcherBelowNode` to false for the LayerTree will force the rendering in the context menu. Setting it to `true` (default) will enforce the old behavior.
This is related to #274 since this should bring better perfomance for the LayerTree since the radios are not rendered directly at the node and the update frequency should be lower. Also should improve the jumping behavior as reported in #287.   
This also ensures that the activated style is shown next to the layer name in the layer tree node for the case that the style switcher is only available in the context menu and not permanently visible. …
=> Make style switcher usable in LayerTree context menu

app/controller/button/FeatureSelectionButtonController.js
Avoid errors if the queryLayer is not set. 
Rename file to match controller name so it is loaded correctly. 
Increase setTimeout to `100` so when used in a `segmentedbutton` there is no race condition that reactivates map tools.
=> Minor FeatureSelectionButtonController fixes

app/view/main/Map.js
This allows reuse of all the code previously in `items` for any derived applications.
=> Allow use of a default map if supplied in a derived class

app/controller/button/DigitizeButtonController.js, app/controller/button/FeatureSelectionButtonController.js, app/controller/button/SpatialQueryButton.js, app/controller/button/StreetViewTool.js, app/view/button/SpatialQueryButton.js
Call the de-toggle methods in the `onBeforeDestroy` handler to ensure `defaultClickEnabled` is set back to `true` when buttons are destroyed when their parent forms are destroyed.
=> Ensure map tools are re-enabled when buttons are destroyed

app/view/main/Map.js
As per comments in #330 - allow `items` to also be overridden
=> Allow items to be overridden in derived class

app/factory/Layer.js, resources/data/layers/default.json
Remove references to legacy OL2 properties - `numZoomLevels`, `zoomOffset`, and `resolutions`, and add in an `extent` option.
=> Update OpenLayers config options

app/plugin/ExpandPanel.js
In some situations* the underlying parent form appears on top of the expanded window. The `modal` setting *seems* to stop this. 
*may be related to using a grid row editor and cancelling or updating the edit after expanding the grid.
=> Set Expander window to modal

app/controller/form/Login.js, app/view/form/Login.js
Some users experienced an issue where the password manager of their browser would fill in the credentials for them, but the UI wouldn't react properly since no "event" (typing) actually occurred on the form, hence the native validation wouldn't kick in and the "Login" button wouldn't be enabled for them.
=> Login form validation modified

app/view/fileupload/FileUploadWindow.js, app/view/fileupload/FileUploadWindowController.js
Fixed a typo that prevented the attachments from being downloaded immediately after the upload. Also 'asterisks' added to fields label to highlight mandatory fields.
=> File upload fixed

app/plugin/ExpandPanel.js
The parent window appearing through the expanded window seems to be caused by the menu keeping a reference to its initial parent and not by #336 (which has been rolled back).
Resetting the menu on the button after the expander panel has been created and also on the restore (using `expand` and `restore` gets around the issue:
```
var destroyMenu = false;
menuButton.setMenu(menuButton.getMenu(), destroyMenu);
```
However on the `restore` event we need to make sure the expand window has not yet been destroyed or there are errors relating to resetting the z-indexes - hence destroying the window once the event has been fired.
=> Fire restore event before parent window is destroyed in CpsiMapview.plugin.ExpandPanel

azure-pipelines.yml
Azure Pipelines keeps failing - possible due to a corrupt zip in the cache
Updating keys should clear the cache (there is no way in the UI according to https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#can-i-clear-a-cache
=> Update cache keys to clear cache

app/controller/window/MinimizableWindow.js
Trigger the restoreFromWindow to remove any associated toolbar button if the window is minimized.
If not an orphaned button remains that causes JS errors when clicked. 
This error was noticed when running https://github.com/compassinformatics/cpsi-mapview/blob/6447240404553f0fe66d9f0134eb8cecc69ac3fd/app/controller/button/StreetViewTool.js#L155
=> Restore Minimizable window before closing

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js
The draw layer style and results selection style can now both be set when configuring the button, rather than hard-coded in the controller
=> Allow styles to be configured on button

app/view/combo/Gazetteer.js
Avoid an empty loading store when clicking the dropdown arrow.
=> Only show Gazetteer dropdown when text is entered

app/controller/button/DigitizeButtonController.js
The custom `featuresupdated` event now includes a `modifications` object which returns the original length prior to the solve, and the new length (to be able to make comparisons), and also the original solver points and new solver points. This allows listeners to see if the start or end moved (and also any of the other points between). 
Example of checking if a point has moved:
```
var modified = false;
// measures can be different on successive calls without moving
// due to floating point / accuracy
// e.g. 456.20598813959714 !== 456.2058558695877
if (p1.get('edge_id') !== p2.get('edge_id') ||
Math.round(p1.get('measure_along')) !== Math.round(p2.get('measure_along'))) {
modified = true;
}
```
=> Add custom object to featuresupdated event with modification details

app/controller/grid/Grid.js
If non-spatial tools are added then the guard should be removed. "Zoom to Feature" will still remain hidden.
=> Hide the context-menu for non-spatial grids

app/controller/button/DigitizeButtonController.js
The polygon and circle tools will still leave the polygons visible when deactivated. The solver points however should not be visible when switching between map tools.
=> Hide the point drawLayer when the tool is not active

app/controller/button/StreetViewTool.js
If `layerGroupName` is not set the icon layer is never added to the map and is not displayed. This pull request adds it directly to the map in this case. 
```js
{
xtype: 'cmv_streetview_tool',
toggleGroup: 'map',
layerGroupName: 'Layers' // no longer required if adding directly to map and hiding from the layer true
}]
```
=> Add StreetView icon layer root map if no overlay group is provided

app/view/menuitem/LayerGrid.js
Allow the spatial selection tool to remain active when the window is minimised rather than closed.
=> Deactivate Spatial Tool on Close rather than Hide

app/controller/grid/Grid.js
If paging is disabled then also add the message to try with it turned off.
=> Display an empty grid message if the WFS request fails to load

app/plugin/FeatureInfoWindow.js
This ensures the form cannot get larger than the window when many fields are returned, and allows the user to position the window without it re-opening it in the centre every time it is closed.
=> Reuse the Info window, limit its height, and add scrolling

app/view/main/Map.js
Currently any state change triggers the event, and causes the following error as the state object is expected to contain center etc. 
`[E] Error while running task - TypeError: Cannot read property '0' of undefined`
=> Only update permalink when the map state changes

app/controller/grid/Grid.js
Id column is always loaded by default so no need for a `store.reload`
=> Avoid store reload when Id column is displayed

app/model/FeatureStoreMixin.js
Changes EOL from CRLF to LF. Relevant code change is:
```js
// if the extent is a single point then buffer it by the extentBuffer property
if (bounds) {
if (bounds[3] - bounds[1] === 0 || bounds[2] - bounds[0] === 0) {
bounds = ol.extent.buffer(bounds, me.extentBuffer);
}
}
return bounds;
```
=> Buffer point extents for zooming

app/controller/MapController.js
=> Fix IE11 "null" displaying on measure strings

sass/src/view/main/Main.scss
- Increase button size
- Add a border around the button
- Fix for IE11. `top: unset !important;` meant the taskbar was invisible. Updated to `top: auto !important;` which should be the equivalent, but also works correctly in IE11. See https://stackoverflow.com/questions/48425453/ie11-css-alternative-to-unset
=> Taskbar CSS Updates

app/util/WmsFilter.js, app/view/menuitem/LayerLabels.js
Fixes a bug where turning on labels didn't correctly duplicate filters.
Also standardise line endings.
=> Ensure LAYER param is updated prior to duplicating filters

app/plugin/FeatureInfoWindow.js
Switch the `CpsiMapview.plugin.FeatureInfoWindow` plugin from using a map `singleclick` event to using the `cmv-mapclick` event. 
This allows more fine-grained control over when the feature tool is activated. For example a derived application can implement a listener such as:
```js
listeners: {
'cmv-mapclick': {
fn: 'onMapClick',
options: {
priority: 500
}
}
},
```
To allow clicking on vector features. The `onMapClick` function can then return `false` to prevent the feature info window from popping up.
=> Use cmv-mapclick for handling feature info clicks

app/field/Point.js
This is a new custom model field used to link a feature store containing points in the same way as `CpsiMapview.field.Line` and `CpsiMapview.field.Polygon`.
=> Add a new point field

app/plugin/BasicTreeColumnLegends.js
When switching styles on a WFS/vector layer, the legend is cached with just the layer name as it has no `layer.getSource().getParams` like a WMS layer. 
The same legend is then used for all styles when switching. 
This pull request checks for an `activatedStyle` (set by the switcher) and then uses this in addition to the layer name to set the cache key.
=> Fix WFS layer switching cache

app/factory/Layer.js, app/plugin/BasicTreeColumnLegends.js, app/view/layer/StyleSwitcherRadioGroup.js
TLDR: When resolution changes for a switch layer the incorrect legend was cached.
Moving from WFS to WMS, the old layer key was used as the new one had not been set. Then `getLegendHtml` in `CpsiMapview.plugin.BasicTreeColumnLegends` would use the old key with the new URL causing the wrong legend to be cached with the image. Simply ensuring the layerKey is set prior to this fixes the issue. 
Pull request also includes:
- changing cache keys to include an underscore for readibility
- typo fix
=> Fix switch layer legend caching

app/view/grid/Grid.js
Still feels slightly "clunky" as it is useful to double-click to select text, but then this also trigges the rowdblclick event.
=> enableTextSelection on grid by default

app/plugin/ExpandPanel.js
A new pre-expand event that may help to resolve an issue with parent forms showing through when an editor is selected.
=> Add a beforeexpand event to Grid Expander

app/plugin/TreeColumnInResolutionRange.js
This PR styles the the layer tree nodes once they are created. Before the layer tree nodes where only styled on resolution change.
Fixes #398
=> Style tree node on initialisation

sass/src/view/main/Main.scss
fixes #380 
Map can be controlled through empty taskbar.
The pointer-events on the taskbar are disabled via CSS and re-enabled on the buttons.
=> Allow clickevents on map through empty taskbar

app/factory/Layer.js, app/view/main/Map.js
This PR reduces the number of unnecessary fired events. 
Before during a zoom in the map, multiple (~ 5) `change:resolution` events were fired. This is a known behavior of OpenLayers (see https://github.com/openlayers/openlayers/issues/7402).
The fix is to use a `moveend` event. This, however, also fires on map-pan events. To prevent them, we check if the resolution has actually changed, otherwise we return.
Now, a zoom on the map fires only one event, like one would expect. This fix should be beneficial for the performance of the app.
=> Prevent multiple resolution change events

app/controller/LayerTreeController.js, app/factory/Layer.js
fixes  #390 
This PR fixes two bugs of the switchlayer:
Scenario 1 "Switchlayer disappears":
- a switch layer is "last" in a group of the layer tree - this means it has the position `0` in the `ol.Collection`
- when the group is expanded, after switch of the layer, something removes this layer from its  `ol.Collection` but still keeps the reference in the treeStore
- replacing `setAt()` with `insertAt()/removeAt()` fixes the problem
Scenario 2 "missing text in layer tree":
- a switch layer is in a collapsed group
- the map resolution changes so that the switch layer changes
- its group in the layer tree is expanded
- then the name of the layer is not displayed anymore
- the problem is solved by re-adding the layer configuration its node in the treeStore
@geographika could you test this …
=> Fix disappearing switchlayer and its text in layer tree

app/factory/Layer.js, app/util/SwitchLayer.js, app/view/layer/StyleSwitcherRadioGroup.js, app/view/main/Map.js, test/spec/util/SwitchLayer.spec.js
This PR refactors the SwitchLayer functionality:
- the essential functionality has move to a new `SwitchLayer.js` util
- functions and constants have been extracted and documented
- some internal cleanup and logical grouping of code parts
- `SwitchLayer.spec.js` contains tests for the new util
The function `SwitchLayer.changeInternalLayer()` shares some code with `StyleSwitcherRadioGroup.onStyleChange()`, but there are still some substantial differences. Therefore, I am not sure if a potential reunion of some code would actually simplify things.
=> Refactor switchlayer

app/controller/LayerTreeController.js, app/controller/button/DigitizeButtonController.js, app/controller/button/SpatialQueryButton.js, app/controller/button/StreetViewTool.js, app/data/model/LayerTreeNode.js, app/model/FeatureStoreMixin.js, app/store/WfsFeatures.js, app/view/combo/Gazetteer.js, app/view/grid/ExampleGrid.js, app/view/toolbar/MapTools.js
This PR moves the layer group of the layer tree down one level. This allows for arbitrary layers to be added to the group without them showing up in the tree.
Additionally this makes the `displayInLayerSwitcher` property unnecessary.
Fixes #352
=> Layer tree as child group

app/Application.js, app/util/ApplicationMixin.js, app/view/toolbar/MapTools.js
Ensure FeatureInfo clicks are only active when no other tools in the `map` `toggleGroup` are active. 
See also #385. 
Also switches ApplicationMixin.js to LF instead of CRLF end-of-lines (hence the large diff).
=> Only trigger FeatureInfo clicks when no other tools are active

app/view/menuitem/LayerLabels.js
This is due to `CpsiMapview.view.menuitem.LayerLabels` expecting a layer with a source, which `ol.layer.Group` does not have.
=> Avoid JS errors when right-clicking on a layer in the tree

app/controller/grid/Grid.js, app/factory/Layer.js, app/model/grid/Grid.js, app/view/grid/ExampleGrid.js, app/view/grid/Grid.js, app/view/grid/GridFiltersExample.js, resources/data/layers/default.json, test/spec/controller/grid/Grid.spec.js, test/spec/view/grid/Grid.spec.js
references #401
This PR is already fully functional for `string` and `number` based filters, but is missing the `list` filter preset.
example configuration:
```json
[...]
"gridFilters": [
{
"property": "code",
"value": "42",
"operator": ">"
},
{
"property": "name",
"value": "old",
"operator": "="
}
],
[...]
```
With the button ":star: Apply Preset Filters", the preset filters can be applied to the grid. See screenshot below.
- This works so far for `number` and `string` filter. 
- basic test classes have been created
**remaining:**
=> Configurable preset filters

app/store/WfsFeatures.js, resources/data/layers/default.json, resources/data/layers/tree.json
- Simplifies tree structure
- Changes ruin layer to `noCluster` to allow grid synch (see #428 notes)
- Set `passThroughFilter` to `true` by default for stores
=> Demo updates

app/view/layer/ToolTip.js
This fixes #224
Somehow extjs seems to have a problem with the very first render. It renders it correctly at first, but a fraction of second later the design changes a tiny bit and the calculated width is no longer big enough. This might as well be a problem with the css eniginge or some obscure css sideeffect that I was not able to find.
I investigated several solutions and debugged the extjs code a little bit, and I abstained from using `width: auto !important` and instead settled for a timeout of 200ms for the first render.
=> Add timeout to first show of tooltip

app/controller/button/DigitizeButtonController.js
This PR disables draw when clicking on an edge for the digitize tool. This is needed if selection of digitized features in the map should be possible.
It also adds a selection model that allows map selection to the digitize button example.
https://github.com/geoext/geoext/pull/690 should be added for a better selection and a bugfix.
Fixes #421
=> disable draw while on edge

app.json, package.json
While investigating the ie11 bug I found out that the openlayers 6.5.0 version we used was not working in ie11. I created a new version that is packaged in `@geoext/openlayers-legacy@6.5.4`.
**Important**: Only the `ol.js` file will work in IE11. The `ol-debug.js` will not work!
=> IE 11 fixes

app/controller/grid/Grid.js, app/util/Grid.js, app/view/LayerTree.js, app/view/grid/Grid.js, app/view/menuitem/LayerFilterReset.js, app/view/menuitem/LayerGrid.js, resources/data/layers/default.json, test/spec/util/Grid.spec.js
references #417 
This PR adds the menu item "Reset Filter".
It removes all filters by calling the [`clearFilters`](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/grid/Grid.js#L594-L612) method of the layer's grid. Additionally, if the layer has preset filters, they will be applied with the [`applyPresetFilters`](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/controller/grid/Grid.js#L731-L735) method afterwards.
The menu item is only shown for layers that have a grid. And additionally if one of these conditions are fulfilled:
- the layer-config contains "preset filters"
OR
- the layer is currently filtered
For checking if the layer is currently filtered it is necessary to create the grid earlier. That's why the creation of the grid in the …
=> Add "Reset Filter" menu item on layer tree

app/controller/grid/Grid.js, app/util/Layer.js, resources/data/layers/default.json
Fixes #430 by ensuring the raw cluster source is used. 
Also removes redundant `vectorSource.clear()` calls as this is called within `vectorSource.refresh()`. 
@simonseyock - there is a comment at https://stackoverflow.com/a/57509897:
> I will just add, that in OL6 this has to be indeed replaced with clusterSource.getSource().refresh()
If this is the case it could be useful to add to the release notes on updating to GeoExt4?
=> Ensure cluster layers sync with grid filters

app/util/SwitchLayer.js
There is an issue where the "Loading..." status bar remains stuck. Can be recreated on https://compassinformatics.github.io/cpsi-mapview/ by zooming in to 1:500 scale and then back to 1:250,000. 
This occurs as the map zoom level changes causing the switchlayer to change its source. The original layer has triggered a `loadstart` event but never completes a `loadend` event. This pull request ensures the event is fired and [decrementAndCheck](https://github.com/terrestris/BasiGX/blob/d1f904c178f87fabb52c6ef43c1b5ee59c9d7e9e/src/view/MapLoadingStatusBar.js#L265) is called in `BasiGX.view.MapLoadingStatusBar`. 
I originally considered trying to add `change:visible` event handlers to `BasiGX.view.MapLoadingStatusBar`, but this issue may only be applicable to switch layers.
=> Ensure switchlayer loadstart events have corresponding loadend event

app/controller/button/StreetViewTool.js, app/view/button/StreetViewTool.js
With the switch to putting the tree in a group layer in #403, the code to add the StreetView layer can be simplified. It can be hidden from the layer tree like other tool layers (measure, gazetteers etc.). 
However as per #427 the icon is no longer appearing when clicking on the map. This was also the case prior to any changes in this pull request. 
I'm out of ideas why this is no longer appearing. It seems to be added to the (correct) map, and visible.
=> Simplify adding the StreetView to the map

app/view/lineSliceGridExample/LineSliceGrid.js
Variables were appearing when debugging other issues.
=> Avoid globals in LineSliceGrid example

app/controller/button/DigitizeButtonController.js, app/view/button/DigitizeButton.js
- Use cyan for selections
- Set style to null for demo so default ol styling is used (polygons not displaying with current style)
=> Update Digitising Tool drawStyles

app/controller/button/DigitizeButtonController.js
When using an `ol.collection` for the `drawLayer` with a ` ol.interaction.Modify` duplicated features are added. 
This can be seen when using the polyon tool. The first time a polygon is drawn there are two identical features (with the same `ol_uid`) in the layer source:
https://github.com/compassinformatics/cpsi-mapview/blob/e831849db1e0246e163477786cfab952448e95c1/app/controller/button/DigitizeButtonController.js#L924
When the "Clear All" option is used it tries to remove both features, however when removing the second (duplicate) the following error is thrown:
`Get the following error `TypeError: Cannot read property 'ol_uid' of undefined`
The solution (from trial and error) was to set the interaction to use the `features` rather than `source` setting for the …
=> Use getFeaturesCollection for interactions

app.json, app/overrides/Ext.Base.js, app/overrides/Ext.data.validator.Bound.js, app/overrides/Ext.form.field.Base.js, app/overrides/Ext.grid.RowEditor.js, app/overrides/Ext.grid.column.Column.js, app/overrides/Ext.grid.filters.filter.Date.js, app/overrides/Ext.picker.Date.js, app/overrides/Ext.tip.ToolTip.js
This is a collection of ExtJS overrides that are used in all child applications. 
They are added to the `app.json` file as follows:
```json
"overrides": [
"./lib/cpsi-mapview/app/overrides",
"./lib/cpsi-mapview/app/overrides/Ext.Base.js" // not picked up automatically (as not a standard component?)
],
```
=> Add common Overrides

app/controller/button/DigitizeButtonController.js, app/form/ControllerMixin.js, app/form/ViewModelMixin.js
Ensure that if a model is reloaded in a form then all the tools on the form point to the layers associated with the new model.
=> Ensure all tool layers use new stores when a model is reloaded

app/view/layer/ToolTip.js
Otherwise they are displayed in the wrong location.
=> Use page offset for tooltips to work in IE11

app/controller/button/DigitizeButtonController.js, app/form/LayersMixin.js, app/model/FeatureStoreMixin.js, app/view/layer/ToolTip.js
Ignores interaction `pointerdown` and `pointerup` events otherwise new points would be added to the solver from multiple events rather than just the `singleclick`. 
Pull request also includes:
- some minor comment changes
- remove redundant function
=> Allow digitizing tool to click on existing points

app/controller/grid/Grid.js, app/factory/Layer.js, app/util/Layer.js, app/util/SwitchLayer.js
Adds a `timestamp` property on the vector source that can then be used as a URL parameter to ensure features are requested from the server rather than browser cache. 
This pull request also harmonises the cache-bustin parameter to `TIMESTAMP` for both WFS and WMS.
=> Allow bypassing of vector layer caching

app/controller/button/DigitizeButtonController.js, app/controller/button/SpatialQueryButton.js, app/controller/grid/Grid.js, app/plugin/FeatureAttributeGrouping.js
This change ensures context menus are shown in the correct location in IE11, and has no changes for other browsers.
=> Use pageX and pageY for all context menus

app/factory/Layer.js, app/util/Style.js, test/spec/util/Style.spec.js
This checks if the layer source is clustered, and if it is then it wraps the style function generated from the SLD, and adds a new clustered style for points.
=> Add a new style for clustered layers

app/controller/addWms/AddWmsFormController.js, test/spec/view/addWms/AddWmsForm.spec.js
Following #403 the External Layers folder was no longer visible in the layer tree. This pull request adds it back to the new `map.get('layerTreeRoot')`.
=> Ensure the External Layers group layer is visible in the layer tree

app/controller/grid/Grid.js, app/model/grid/Grid.js, app/view/grid/Grid.js
Allows the contents of the grid to be exported as a zipped shapefile. 
Relies on https://github.com/geoext/geoext/pull/700
This also adds 2 new viewmodel properties that can be used to hide/show the export buttons:
```
exportExcelVisible: true,
exportShapefileVisible: true
```
=> Allow exporting of the grid to a shapefile

app/controller/toolbar/CircleSelectionToolbar.js, app/form/ViewModelMixin.js, app/view/main/Map.js, karma-conf.common.js, test/spec/form/ViewMixin.spec.js, test/spec/form/ViewModelMixin.spec.js, test/spec/view/LayerTree.spec.js
The previous pull request reduced the test coverage, even though more tests were added. 
On each run of the tests (using `karma start karma.conf.js --single-run`) different numbers of tests were run - (worringly) missing tests didn't appear at all in the summary.
On inspection in the browser debugger (`karma start --browsers Chrome --single-run=False --debug --auto-watch`) there were several JS errors relating to viewmodel formulas that required a map etc. 
Once these were fixed the full test suite started running again.
=> Minor fixes to get all tests running

app/controller/LayerTreeController.js, app/controller/form/Login.js, app/controller/panel/NumericAttributeSlider.js, app/form/ControllerMixin.js, app/form/LayersMixin.js, app/form/RightInfoField.js, app/form/ValidationMessagesMixin.js, app/form/ViewMixin.js, app/form/ViewModelMixin.js, app/plugin/ExpandPanel.js, app/plugin/FeatureAttributeGrouping.js, app/store/Readme.md, app/store/WfsFeatures.js, app/view/button/DigitizeButton.js, app/view/grid/ItemDeleter.js
This pull request addresses some of the issues highlighted by @chrismayer in a code review.
The following are addressed:
https://github.com/compassinformatics/cpsi-mapview/blob/master/app/form/ControllerMixin.js#L40
Maybe fire also an event like 'savefailed', like it is done for success case.
https://github.com/compassinformatics/cpsi-mapview/blob/master/app/form/RightInfoField.js#L2
API-Docs are maybe wrong here? I think this is no Mixin, is it?
https://github.com/compassinformatics/cpsi-mapview/blob/master/app/form/ValidationMessages.js#L7
I'd suggest to rename it with a 'Mixin' suffix in the class name to be consistent.
https://github.com/compassinformatics/cpsi-mapview/blob/master/app/form/ViewModelMixin.js#L26
The 'destroyUtil' naming seems non intuitive here …
=> Rename functions and classes for clarity and add docstrings

app/controller/button/SplitByClickButtonController.js, app/field/Line.js, app/form/ControllerMixin.js, app/form/ViewMixin.js, app/model/button/SplitByClickButtonModel.js, app/view/button/SplitByClickButton.js, test/spec/controller/button/SplitByClickButtonController.spec.js, test/spec/view/button/SplitByClickButton.spec.js
* Introduces `splitByClickButton` component which enables to split existing road segments into two parts (public and private) by clicking on the appropriate segment feature on the map
* Concepted to used while operating on `Public/Private Splits` component currently integrated into PMS project
* Additionally enables passing of OpenLayers style function while configuring selectionLayer bound to grid store
Please review @geographika @select-8
=> Introduce splitByClick button

app/controller/button/HelpButtonController.js, app/controller/button/LoginButtonController.js, app/controller/window/MinimizableWindow.js, app/form/HelpMixin.js, app/form/ViewMixin.js, app/view/button/HelpButton.js, test/load-tests.js, test/spec/controller/button/HelpButtonController.spec.js, test/spec/form/HelpMixin.spec.js, test/spec/view/button/HelpButton.spec.js
This moves the logic to open a help link out of the `MinimizableWindow` controller into its own mixin.
This then allows the same logic to be used on a new standalone help button. 
On addition this update uses the following logic in the codebase to allow tests to run successfully, as `Ext.getApplication` is always null:
`Ext.getApplication ? Ext.getApplication() : Ext.app.Application.instance;`
`Ext.app.Application.instance` is set to a simple object in `test/load-tests.js`
=> Add Help mixin

app/controller/LayerTreeController.js, app/model/FeatureEventsMixin.js, app/view/main/Map.js
When running locally (in debug) add console messages warning if any of the model `syncStoreIds` or `syncLayerKeys` are invalid.
Also check all layer keys in the `tree.json` are available as layers from `default.json` -by getting the full list of `layerKey` properties and checking they exist.
=> Add improved error logging for missing layers and keys

app/util/ApplicationMixin.js
Prior to this update the `onAppUpdate` was never called (due to having the same name as a function in [Ext.app.Application](https://docs.sencha.com/extjs/6.7.0/classic/Ext.app.Application.html#method-onAppUpdate).
This adds a hook (and renames the function to distinguish it from its owning class).
=> Ensure onApplicationUpdated is triggered

app/controller/button/DigitizeButtonController.js, app/form/ControllerMixin.js, app/form/ViewMixin.js, karma-conf.common.js, test/load-tests.js, test/spec/controller/button/DigitizeButtonController.spec.js, test/spec/form/ControllerMixin.spec.js
This pull request removes a polygon feature when a user has switched to the point network selection tool after having used the polygon tool. Previously it was left in place and then incorrectly sent to the server. The polygon is only removed when a selection of edges is created. New behaviour shown below:
Tests were added for all new functionlity, and a full build of GeoExt (rather than adding individual files and using `Ext.Loader`) is used by the test suite which seems to have resolved the `Duplicate class name` errors (at least when running from the console).
=> Remove polygon when switching to point digitizing tool

app/controller/button/StreetViewTool.js
`updatePositionFeature` was sometimes called when `me.svPanorama` was null leading to JS errors. 
1. Open SV window
2. Close SV window
3. Open a grid window. Use Export to Excel from a grid to force a download which resizes the browsers (as in image below):
Call stack:
```
Uncaught TypeError: Cannot read properties of null (reading 'getPov')
at constructor.getHeadingRad (app.js?_dc=1632146254785:98006)
at constructor.updatePositionFeature (app.js?_dc=1632146254785:97990)
at constructor.handlePovChanged (app.js?_dc=1632146254785:98000)
at Wf.pr (js?v=quarterly&key=AIzaSyCmQRf1m6EISENeiijFjza18iIyrIQiArQ&_dc=1632146254785:232)
at Object._.I.trigger (js?v=quarterly&key=AIzaSyCmQRf1m6EISENeiijFjza18iIyrIQiArQ&_dc=1632146254785:228)
at cg …
```
=> SteetView window null fix

app/form/ViewMixin.js, test/spec/form/ViewMixin.spec.js
An initial atempt to resolve #485 without requiring any dependent code to be changed. 
A view can now have a new `customButtons` property which the `CpsiMapview.form.ViewMixin` will use to insert additional buttons into the toolbar:
```
customButtons: [
{
index: 2,
button: {
xtype: 'button',
itemId: 'customExporter',
text: 'Custom Button',
handler: 'onCustomExport',
bind: {
disabled: '{!canCustomExport}'
}
}
}
],
```
The array has objects containing the `index` where the button should be inserted, and a `button` config with the button `xtype`. 
Default buttons are cloned to avoid modifying the `defaultButtons` proptotype and applying to all forms that use the mixin.
=> Allow insertion of custom buttons in toolbar

app/form/field/LengthField.js
Introduce `lengthField` component which enables simple and quick formatting of measurement fields.
By default, input value `100` becomes `100.00 m` after format is applied.
Please review @geographika
=> Introduce LengthField

app/controller/button/DigitizeButtonController.js
Properly cleanup result layer for current active group also for features which don't have property `group` set.
Needed for update of road segment features retrieved by `pmspy/edgesolver` endpoint.
Please review @geographika
=> Fix feature cleanup if no group prop is set

app/overrides/Ext.grid.filters.filter.Date.js
If the date filter is remote (mapserver) we need to convert to a string, if local we lave as a js date object
=> date filter overrides should check if request is remote

karma.conf.js
See issue at https://github.com/karma-runner/karma-coverage/issues/432
This doesn't resolve #486 but at least will distinguish between failing tests and reduced coverage.
=> Warn instead of failing tests due to coverage changes

app/form/ControllerMixin.js
Encountered situations where the model was valid but clicking the save button did nothing. 
`f.isValid()` returned false, but when validity was refreshed it returned true.
=> Ensure validation is in sync

app/controller/button/DigitizeButtonController.js
When drawing features "locally" (without triggering server-side services) fire a new `localdrawend` event. This captures both draw end and when a drag and drop of a feature occurs (by checking the `pointerup` event. 
See http://jsfiddle.net/48ykaLhq/ for modifying the pointer interaction events. 
Note when using `handleEvent` it appears the other events (https://openlayers.org/en/latest/apidoc/module-ol_interaction_Pointer.html) e.g. `handleUpEvent` are no longer fired. 
See also https://github.com/openlayers/openlayers/issues/4509
=> Fire a custom localdrawend event

app/form/ControllerMixin.js
Previously `form.isValid()` was checked in this function, but values on a tab that has not been displayed are only bound later, so this incorrectly returns that a form is invalid. 
Check the model validity instead (although the button should be disabled if the model is not valid).
=> Check model rather than form validity

.eslintrc.js, app/factory/Layer.js, karma.conf.js
Adds a new layer config setting `"requestMethod": "POST"` that can be set on WMS layers to use `POST` rather than the default `GET` requests. 
This fixes the issue where the URL querystring is too long to be handled by the server due to large attribute and spatial query filters. 
The `debounce` function is also updated to take this into account.
=> Allow POST requests for WMS layers

app/controller/MapController.js
Allows child applications to extend from this controller and configure vector features to be clicked and open an associated edit form.
=> Add generic map click handling for layers

app/view/LayerTree.js
When searching the tree if a layer and a group layer have the same name then the group layer may be incorrectly returned by `getNodeForLayer`.
=> Ensure group layers are excluded when finding a node

app/view/LayerTree.js
An improvement on #535 - use the unique `layerKey` property specified in the `default.json` layers config file, rather than the layer `name` property for finding layers. This will always be unique, and avoids any issues where two layers have the same name.
=> Use layerKey rather than name for finding layers

app/controller/button/DigitizeButtonController.js
Otherwise the the `defaultClickEnabled` property remains set to false even though the digitising tools are no longer active.
=> Fire toggle event when the DigitizeButtons are destroyed

app/factory/Layer.js
Allows the config file to set custom tile grids (for example in other projections) in the layers config file.
E.g.
```json
{
"layerType": "xyz",
"layerKey": "CUSTOM_TILES",
"openLayers": {
"opacity": 0.7,
"visibility": false,
"projection": "EPSG:2157",
"tileGrid": {
"origin": [ -5022200.0, 4821100.0 ],
"resolutions": [
1058.3354500042335,
661.4596562526459,
330.72982812632296,
158.75031750063502,
105.83354500042334,
52.91677250021167,
26.458386250105836,
13.229193125052918,
6.614596562526459,
2.6458386250105836,
1.3229193125052918,
0.6614596562526459,
0.26458386250105836
]
}
},
"url": "http://example.com/arcgis/{z}/{y}/{x}"
}
```
Resoultions and origin taken from an [ArcGIS Server Metadata page](https://webcache.googleusercontent.com/search?q=cache:jzPnfcqUP8gJ:https://gsi.geodata.gov.ie/s …
=> Add custom tileGrid support for xyz layers

app/controller/button/DigitizeButtonController.js
Fix to #537 to ensure the button property is set to false before recalculating `defaultClickEnabled`
=> Ensure button pressed property is set to false prior to firing event

app/util/ApplicationMixin.js, app/view/main/Map.js
This update allows a map to set custom properties, such as a projection, on the map view, using a new `mapViewConfig` object.
For example to have a custom projection:
```js
Ext.define('Example.view.main.Map', {
extend: 'CpsiMapview.view.main.Map',
xtype: 'example_map',
..
mapViewConfig: {
projection: 'EPSG:2157',
zoom: 11,
center: [616038, 629971]
},
```
=> Allow custom map view properties to be set

app/controller/grid/Grid.js, app/util/Layer.js, app/util/SwitchLayer.js, app/util/WmsFilter.js, app/view/menuitem/LayerLabels.js, test/spec/util/Layer.spec.js, test/spec/util/WmsFilter.spec.js
This allows vtwms layers to be used in synch with the grids in the same way as wms layers.
=> Allow vector tile layers to be synched with grids

app/form/ControllerMixin.js
This avoids having to check for specific viewmodel properties, and means tools added in derived applications are also updated without requiring them to be added to this function.
=> Ensure layers are reset for all digitising tools in a form

app/factory/Layer.js, app/view/LayerTree.js, app/view/menuitem/LayerHelp.js, test/spec/view/menuitem/LayerHelp.spec.js
Adds a new layer context-menu item "Help" that opens a help page in a new browser window.
The `helpUrl` can be set either in the layer configuration, and if this is missing and there is a grid associated with the layer (via the `gridXType` config option) and the grid view model with a `helpUrl` property then this is used.
=> Add new Help menuitem

app/overrides/Ext.window.Window.js
Ensure dragging a window works correctly when the initial `defaultAlign` is not the default `'c-c'`
=> Add window override to fix ghost position

app/controller/grid/Grid.js
This can be undefined if the grid has not been created and the store is not set (but updating an associated model attempts to reload the grid store).
=> Ensure the loadWfs function exists before calling

app/util/ApplicationMixin.js, app/view/button/DigitizeButton.js, app/view/toolbar/MapTools.js
Add a new example pan tool (which is simply a button that deactivates other tools, as pan is the default OL action), and exclude this when searching to see if any tools are active.
=> Add a new example pan tool 

app/util/Layer.js
This will also update any associated legend image. Legend images can become broken if a user access token expires prior to requesting a layer, so this allows them to be re-requested. 
As part of this update, also fix a UI glitch where the original layer glyph was removed when applying and then removing a filter.
=> Refresh layer node when using the Refresh plugin

app/form/ValidationMessagesMixin.js
The `ValidationMessagesMixin` gets the view from the form field which triggers the `onFieldChanged` event. 
In the case of a combobox in a grid, the `me.getView()` returns the grid component rather than the window (even though `me` is the same form controller in both cases) - the `saveButton` is not found. 
Unsure if `.getView` returning different views from the same controller is by design in ExtJS or not. 
Also ensure that the `debug` statements wraps the `log.warn` rather than the actual `return` statement or it is not called and an error is thrown.
=> Get parent window if control is in a sub-component

app.json, app/factory/Layer.js, package.json
Requires new `olStyleFunc.output` rather than `olStyleFunc` (since v.3.0.0 of GeoStyler parsers - see https://github.com/geostyler/geostyler-sld-parser/releases/tag/v3.0.0)
=> Update GeoStyler libs and move libs off CDNs

app/factory/Layer.js
The MapServer scripts used to generate SLD all use 1.1.0. Without setting the parser version polygons are not displayed correctly.
=> Set SLD version to 1.1.0

app/form/field/Combo.js, app/form/field/ComboLegacy.js, test/spec/form/field/Combo.spec..js, test/spec/form/field/ComboLegacy.spec.js
These allow a consistent UX across the applications by using the same defaults, fix an issue with binding, and also includes a ComboLegacy class that allows legacy options that display for existing records, but cannot be selected for new records.
=> Add customised combobox classes

app/Application.scss, app/factory/Layer.js, app/util/SwitchLayer.js
This fixes a bug where after zooming in on a switch layer (changing from WMS to WFS), the WFS symbology was incorrect and displaying the older style. 
This was due to refreshing the layer before the `loadSLD` callback had completed. The refresh code was moved to the callback function. 
Other changes were for variable clarity while debugging the code.
=> Ensure SLD loaded correctly on a switch layer

WEB-INF/web.xml, app/Application.js, app/controller/button/LoginButtonController.js, app/model/toolbar/MapTools.js, app/util/ApplicationMixin.js, app/view/toolbar/MapTools.js
This update allows the demo application to connect to a set of development backend services. These include:
- authentication (to return a token that can then be used to access further services)
- backend Python tools to create routes
When working locally with the Sencha development server the following command should be used to run the demo app:
`sencha app watch  --j2ee`
This flag allows the `WEB-INF/web.xml` file to be used which proxies service calls to the backend development server. 
It does not seem possible to proxy back to the development server directly using https, so an additional local proxy is added, to make the following URLs available at http://localhost/WebServices and http://localhost/pmspy. 
These could be added to …
=> Allow connection to protected services

app/controller/button/DrawingButtonController.js, app/view/snappingExample/EdgeButton.js, app/view/snappingExample/EdgeWindow.js, app/view/snappingExample/EdgeWindowController.js, app/view/snappingExample/EdgeWindowViewModel.js, app/view/toolbar/MapTools.js, resources/data/layers/default.json, resources/data/layers/tree.json
This pull request adds 2 vector layers - nodes and edges, that can be used with a new example snapping form and tool. 
Clicking the button highlighted below opens a new "Snapping Example" window. 
Activating the "Draw Edge" tool then allows a user to turn on the Nodes and Edges layers and connect them. The start and end features are then displayed in the form. 
Note, this pull request relies on https://github.com/compassinformatics/mapview-demo/pull/5 (already deployed to the development MapServer). 
TODO (in subsequent pull requests):
- add WFS styling to the new layers
- add unit tests
- add icon to the "Draw Edge" button
=> Add Example Snapping Tool and Window

app/controller/LayerTreeController.js, app/factory/Layer.js, app/util/RoleManager.js, app/view/LayerTree.js, test/spec/util/RoleManager.spec.js
- fixes #562 
- works on login and logout
- also works for groups
- also tested on switch layers
- for testing:
- set the cookie `roles` to something like `EDITOR_ROLE,DUMMY_ROLE` 
- add the property `requiredRoles` to layer items in `tree.json`, like below :
```json
[...]
{
"id": "LA_SITES",
"text": "Local Authority Sites",
"leaf": true,
"requiredRoles": ["READER_ROLE"]
},
{
"id": "RUINS_WFS",
"leaf": true,
"text": "Ruins",
"qtip": "Right-click for a layer grid",
"requiredRoles": ["ADMIN_ROLE"]
},
{
"id": "my-group",
"title": "My Group",
"expanded": true,
"checked": false,
"requiredRoles": ["EDITOR_ROLE"],
"children": [
{
"id": "EDGES_WFS",
"leaf": true,
"text": "Edges",
"qtip": "Used in the snapping tool example"
},
{
"id": "NODES_WFS",
"leaf": true,
"text": "Nodes",
"qtip": "Used in …
```
=> Layertree: only show layers that user is allowed to see

app/view/snappingExample/EdgeButton.js, app/view/snappingExample/EdgeWindow.js, resources/data/layers/default.json, resources/data/layers/tree.json
Relies on the test dataset in https://github.com/compassinformatics/mapview-demo/pull/6
Adds a new polygon layer for snapping and retrieving IDs.
=> Add polygon example layer to snapping tool example

app/controller/button/DrawingButtonController.js, app/util/Style.js, app/view/button/DrawingButton.js, resources/data/layers/default.json
- references #564 
- snapped node or edges are highlighted
- provides various configurable styles for editing
- todo:
=> Drawing Tool Improvements

app/controller/LayerTreeController.js
Quick fix for #581. This simply removes trying to handle setting layer visibility in the filter. 
The initial rationale was to handle the case where a user logs out and then logs back in after their user roles have been modified (without refreshing the browser). This use case may never happen, and even if it does, then changing which layers are visible in the application may be more confusing than helpful. 
Removing this logic keeps things simpler, and all that is lost is layers with visibility set to `true` by default have to be switched on manually in the case when logging in and out with different roles.
=> Remove setting of layer visibility from layer tree filter

app.json, app/controller/LayerTreeController.js, app/controller/addArcGISRest/AddArcGISRestFormController.js, app/view/LayerTree.js, app/view/addArcGISRest/AddArcGISRestForm.js, package.json, test/spec/view/addArcGISRest/AddArcGISRestForm.spec.js
This introduces the `cmv_add_arcgisrest_form`, which is an example implementation for importing layers via the ArcGIS Rest API.
This makes use of the not yet published `basgix-form-addarcgisrest` component (see https://github.com/terrestris/BasiGX/pull/691). So this PR will remain WIP until released. However, this PR can already be reviewed, as the application logic itself should not change anymore.
Multiple screencasts can be seen in https://github.com/terrestris/BasiGX/pull/691
This PR differs by adding English translations:
Note: I added the `url-polyfill` lib, since BasiGX now makes use of the `URL` interface, which is not supported by IE.
This (partially?) solves https://github.com/compassinformatics/cpsi-mapview/issues/561
=> introduces cmv_add_arcgisrest_form

resources/data/layers/default.json, resources/data/layers/tree.json, resources/data/styling/Cycleways.xml, resources/data/styling/Footways.xml, resources/data/styling/Services.xml
3 new line vector layers have been added to the demo MapServer (and deployed) via https://github.com/compassinformatics/mapview-demo/pull/7
@JakobMiksch - these layers are representative of some of the features we will be attempting to trace using #560. 
This pull request adds them to the layer tree, with basic SLD styles. It also moves all the vector testing layers to a subfolder. 
@JakobMiksch @jansule - let me know if it is ok to merge this, or if I should hold off while you are testing.
=> Add 3 new edge vector layers and styles

app/controller/LayerTreeController.js
This applies the preset filters when loading the layer tree. Before this, the filters were only applied when the layer grid was opened.
Solves https://github.com/compassinformatics/cpsi-mapview/issues/573
=> Apply preset filters when loading layer tree

app/controller/LayerTreeController.js, app/form/LayerTreeFilter.js, app/util/LayerTreeFilter.js, app/view/form/LayerTreeFilter.js, app/view/main/Main.js, test/spec/util/LayerTreeFilter.spec.js
- fixes #484
- adds textfield for filtering by layer name
- adds checkbox to filter by visible layers
- adds a config if baselayers should be filtered or not (defaults to `true`)
=> Add filter to layer tree

.github/workflows/on-pull-request.yml, .github/workflows/on-push-master.yml, karma.conf.js
Hopefully setting `statements` means CI will not produce errors unless it falls below the 15% threshold.
=> Re-enable test coverage

app/controller/grid/Grid.js
In cases where a grid has mixed entity types, and in cases where Ids in a mixed grid may be negated to avoid Id conflicts, this PR  spits out some of the logic from `onRowDblClick` into `getRecordEditConfig` which is intended to be overridden in a subclass if needed.
Example usage:
```javascript
Ext.define('Pms.view.grids.CombinedEdgesGridController', {
extend: 'CpsiMapview.controller.grid.Grid',
alias: 'controller.pms_combinededgesgrid',
requires: [
'CpsiMapview.controller.grid.Grid'
],
// override the method in the parent class to apply custom logic
// in this mixed grid
getRecordEditConfig: function (vm, record) {
var id = record.getId();
return {
associatedEditWindow: vm.get('associatedEditWindow'),
associatedEditModel: vm.get('associatedEditModel'),
id: Math.abs(id)
};
},
});
```
=> Split out part of onRowDblClick in cmv_grid to allow for custom logic when determining associatedEditWindow and record Id 

app/plugin/FeatureInfoWindow.js, app/view/main/Map.js, test/spec/plugin/FeatureInfoWindow.spec.js
A `ol.source.ImageWMS` can combine multiple WMS layers e.g. `params: { 'LAYERS': 'river,road'}`.
If the properties for the combined features don't match, then MapServer throws an error. This pull request splits each of the layers in `params.LAYERS` into a separate call to avoid this.
=> Allow GetFeatureInfo requests on layers with combined WMS layers

.gitignore
Changing `ext/` to `ext` in gitignore will ignore ext if it is a folder or a symbolic link
=> Ignore ext when it is a symbolic link

app/controller/button/DrawingButtonController.js, app/controller/button/TracingMixin.js, app/view/button/DrawingButton.js
Fixes #598 
- Makes snapTolerance configurable to allow easier drawEnd doubeclick
- Returns early from onTracingMapClick if drawing is finished to prevent conflicts
- Protects against undefined updatedCoords which cases console errors when tracing certain features
=> Fix issues with tracing drawEnd, make snapTolerance configurable

.gitignore, app/controller/button/DrawingButtonController.js, app/view/button/DrawingButton.js
Currently when snapping is set up in `cmv_drawing_button` and one of the configured snapping Layers is turned off, the snap interaction will still snap to the features of the invisible layer.
This PR adds option `allowSnapToHiddenFeatures` which defaults to `true` (current behavior)
If set to `false`, the snapCollection collection will be updated accordingly depending on layer visibility.
=> Add option to only snap to visible layers/features

app/model/FeatureEventsMixin.js, test/spec/model/FeatureEventsMixin.spec.js
Switch layers are always logging error output when either the WMS or WFS aren't loaded. Ensure only valid errors are logged.
Also run a basic test so this code is run.
=> Clean up error log output in FeatureEventsMixin

app/plugin/FeatureInfoWindow.js, app/util/WmsFilter.js
When checking for layer names and duplicates should be ignored as we only want a single set of results.
If multiple layer names are used then we need to attempt to also set the correct style and filter for the layer to avoid backend MapServer errors such as:
`msWMSLoadGetMapParams(): WMS server error. Invalid style (Basic,labels). Mapserver is expecting an empty string for the STYLES : STYLES= or STYLES=,,, or using keyword default  STYLES=default,default, ...
`
=> Handle GetFeatureInfo requests when labels are turned on

app/controller/button/DrawingButtonController.js
Currently with the `cmv_drawing_button`, you can only append to the last point of a previously drawn line. If you try to append to the start point, it will create a new line:
https://user-images.githubusercontent.com/1889044/200355790-b08c6c50-6bf0-4795-a378-19a59338078e.mp4
With this PR, you can append to either start or end of the previous line. If appending to the start, the coords of the previous line are reversed so the we end up with a single line with one start and one end point.
https://user-images.githubusercontent.com/1889044/200356769-14567c54-d1ea-41f7-a4e2-6e14624e1ca7.mp4
=> Allow merging to both start and end of existing line

app/form/LayerTreeFilter.js
This readds the logic for clearing a filter in the filter tree.
solves https://github.com/compassinformatics/cpsi-mapview/issues/594
=> Readd wrongly removed clearText handler

app/view/form/LayerTreeFilter.js
Now the clear function is back, make this the default - see #594
=> Show the hide trigger button by default

app/factory/Layer.js
Fire the `vectorloadend` so the loading bar knows when to close, otherwise when zooming in on a switch layer the loading bar doesn't disappear.
=> Hide the loading status bar when a request is aborted

app/plugin/TreeColumnInResolutionRange.js
Fixes #629 
Everything worked as expected up until `node.triggerUIUpdate()`. The UI/tooltips didn't update as they did before, maybe a change in ExtJS itself?
Setting the `qtip` instead updates the tooltip as expected.
=> Set qtip to fix issue where tooltip is not updated

app.json
See https://stackoverflow.com/questions/75179573/how-to-fix-loading-the-google-maps-javascript-api-without-a-callback-is-not-supp
=> Fix for Google API

app/util/ApplicationMixin.js
Related to #637 - if no login form is used then when attempting to get the application the following line returns null:
https://github.com/compassinformatics/cpsi-mapview/blob/b9d088cb4cf169e8262a54e4646a71b3f3b28108/app/view/main/Map.js#L222
There is then a JS error at:
https://github.com/compassinformatics/cpsi-mapview/blob/b9d088cb4cf169e8262a54e4646a71b3f3b28108/app/view/main/Map.js#L270
This fix delays the creation of the application and appears to resolve the issue.
When a login screen is used then `me.doLogin()` is called and the timing of the application creation seems fine. This is set in `ApplicationMixin.js` with `requireLogin: true`.
=> Ensure the page is loaded before creating application

app/util/MenuMixin.js, app/view/menuitem/LayerGrid.js
This PR allows a grid window title to be set to a custom value in the scenario where the layer doesn't exist in tree.json (currently where the window title is retrieved from)
Usage:
```
this.showGridWindow(layerKey, 'My Custom Title')
```
=> Add showGridWindow titleOverride option

app/form/ViewMixin.js, app/form/ViewModelMixin.js
This PR allows individual form windows hide the padlock icon even if `Application.enableIsLocked` is true. 
To hide the padlock icon for a particular window, set create formula `isPadlockVisible` and return false
=> Move padlock hidden binding to a formula so it can be overridden

app/form/field/NumericField.js
This PR forces `CpsiMapview.form.field.NumericField` to have a numeric value if `allowBlank === false`.
Currently if you use keyboard backspace or delete to clear the field, the field will be cleared regardless of `allowBlank` or `minValue` settings, and the underlaying model value will be 0, not null as might be expected.
=> Force number for NumericField with allowBlank false

app/controller/grid/GroupEditMixin.js
This displays a text box to allow group edits to grid records that require a numeric value.
A `maxLength: 5` validation is applied to the text box by default.
=> Allow a numeric group update

app/form/field/ComboLegacy.js
This PR prevent users selecting  isLegacy records in cmv_combolegacy.
It only does so during user interacts (user is focused on the input)
Programmatic changes will be ignored (e.g. clicking the Refresh button, since the combo will have lost focus)
=> Prevent user selection of isLegacy records

app/controller/button/LoginButtonController.js, test/spec/controller/button/LoginButtonController.spec.js
This PR allows roles other than Browser_ prefixed roles to display in the user details tooltip of the login button.
Prefixes can be customised with the `displayRolePrefixes` property in application.js, e.g.
```
displayRolePrefixes: ['Browser_', 'External_']
```
=> Allow customising role prefixes

.gitignore, README.md, package-lock.json, package.json
- updates `proj4js` to latest version
- moves the linting dependencies to `devDependencies`
- moves `browserify` to `dependencies`. This was moved as `npm install` was giving me:
```
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run build:turf
npm ERR! > @compassinformatics/cpsi-mapview@1.3.0 build:turf
npm ERR! > browserify turf-builder.js -s turf > lib/turf.js
npm ERR! 'browserify' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```
The package-lock.json has also been added to the project (and removed from .gitignore). 
Also bumps the mapview version to 1.3.1.
=> Dependency updates

app/controller/grid/Grid.js
A follow-up to #410 - this allows preset filters to be added to a boolean column in a grid/layer.
A sample config is shown below. The value can be set to "1"/"0" or "true"/"false". The value can also be without quotes. 
```json
{
"layerType": "wms",
"layerKey": "MY_WMS",
"gridFilters": [
{
"property": "IsActive",
"value": "1",
"operator": "="
}
],
```
One minor issue is that the filter UI does not populate correctly in the grids (the filter is set to "No" in the UI, but the value is "Yes" (1). This is the same whether quotes are used around the value or not.
=> Allow boolean filters in preset filters

README.md, karma-conf.common.js
Allows running of a single test e.g. `karma start --single-run --grep 'CpsiMapview.factory.Layer'`
=> Add grep option to karma testing

app/controller/button/DrawingButtonController.js, app/view/button/DrawingButton.js, app/view/snappingExample/EdgeWindow.js, resources/data/layers/default.json, test/spec/controller/button/DrawingButtonController.spec.js
Currently, if a user doesn't have a vector node layer switched on, and they snap to the end of a line, an edge Id is returned. 
This will require a line to be split if the drawn lines are required for routing - even though the new line snaps to a node. 
This pull request allows node Ids to be picked up from the line if a drawn line snaps to the end. 
A new config property has been added to the tool to set which properties of a line feature contain the node Ids:
```js
edgeLayerConfig: {
startNodeProperty: 'NodeIdFrom',
endNodeProperty: 'NodeIdTo'
},
```
If this is set then node Ids from the line will take priority over the line id. 
The node Ids will have to be added as properties to the line vector layer. This can be set in the `serverOptions` for a WFS layer in the JSON layer config …
=> Snap to ends of lines if node Id properties are present

.gitignore, app/controller/grid/Grid.js
For export functionality, the fileName can be passed to the OUTPUTFORMAT parameter as a runtime substitution. The corresponding block in a MapFile can be configured as so:
```
OUTPUTFORMAT
NAME "xlsx"
DRIVER "OGR/XLSX"
MIMETYPE "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=utf-8"
FORMATOPTION "FORM=zip"
FORMATOPTION "STORAGE=memory"
FORMATOPTION "FILENAME=%filename%.xlsx"
END
```
=> add the WFS typeName as the fileName

app/factory/Layer.js, test/spec/factory/Layer.spec.js
For WFS layers a new config setting can be added to have a permanent filter in a layer:
```
"filters": [
{
"property": "IsActive",
"value": "1",
"operator": "="
}
],
```
This is useful for standalone WFS layers without a grid, but where a filter is required. The filter is added to all requests - including when there are additional WFS filters added - for example the bbox filter.
=> Add support to filter a WFS in the config file

app/util/Grid.js
Otherwise inherited grids can be opened instead of the required grid.
=> Only query exact grid xtypes

app/controller/button/DrawingButtonController.js, test/spec/controller/button/DrawingButtonController.spec.js
These were used by a polygon creation tool that no longer requires "magic numbers" of -2 to indicate new nodes.
Other changes to the file are due to auto-formatting.
=> Remove no longer used magic numbers from digitising tool

app/view/combo/Gazetteer.js, test/spec/view/combo/Gazetteer.spec.js
By default field names are expected to be `minX3857` etc. 
This update allows different suffixes to be added so fields such as `minX2157 can be used, using a new `fieldNameSuffix` config setting on `CpsiMapview.view.combo.Gazetteer`:
Example:
```
{
xtype: 'cmv_gazetteer_combo',
url: '/gazetteer/',
srs: 'EPSG:2157', // also set the project to use for the extents
fieldNameSuffix: '2157',
proxyRootProperty: 'data',
displayValueMapping: 'name',
emptyText: 'Townland...'
}
```
`Ext.create('CpsiMapview.view.combo.Gazetteer', { fieldNameSuffix: '2157' });`
=> Allow suffixes to be added to gazetteer field names

app/controller/button/DigitizeButtonController.js
This PR removes the hard coded geometry3857 JSON parameter name from DigitizeButton and dynamically generates it based on map projection code.
E.g. if map projection is:
EPSG:3857 - param name will be geometry3857
EPSG:2157 - param name will be geometry2157
etc
=> Generate JSON geometry param name from map SRS

app/controller/grid/Grid.js, app/model/grid/Grid.js, test/spec/controller/grid/Grid.spec.js
This PR allows setting of extraPropertyNames in the `cmv_grid` viewModel, which is an array of propertyNames which will be added the currently visible grid columns when the WFS is requested.
Useful for when you need a column/property to be present for background processing but there's no guarantee it will be a visible column
=> Allow defining extraPropertyNames in cmv_grid

app/util/ApplicationMixin.js
Timeout seemed to be ignored when updating `Ext.data.Model` with a `proxy` set. This update ensures the browser doesn't timeout with a "Communication Failure" after the default 30 seconds. 
See also https://stackoverflow.com/a/19565108/179520
=> Ensure increased timeout it used in all cases

app/controller/button/SpatialQueryButtonController.js, app/controller/grid/Grid.js, app/view/grid/Grid.js, test/spec/controller/button/SpatialQueryButton.spec.js, test/spec/controller/grid/Grid.spec.js, test/spec/view/button/SpatialQueryButton.spec.js
Adds a new button to the grid that allows the polygon used for a spatial selection to be removed (without needing to reactivate the tool).
Also adds a new context-menu item to the tool "Cancel Drawing" to cancel drawing the current feature (this should also be possible by pressing the Escape key - an OL default, but this doesn't seem to work). 
@select-8 @fergaldoyle - this button would currently always be visible when this pull request is merged. Should it be optional?
Video of functionality below:
https://github.com/compassinformatics/cpsi-mapview/assets/490840/9fd087ce-7bc2-4679-9c6f-643431ca6533
=> Add Clear button for grid spatial filter

app/view/main/Map.js
This allows an application to increase the hit tolerance when selecting features. The default is set to the OpenLayers default of `0` so any existing applications will be unaffected. 
It can be applied in the ``Map.js`` file of an application which extends ``CpsiMapview.view.main.Map``
```js
mapViewConfig: {
projection: 'EPSG:2157',
zoom: 11,
center: [616038, 629971],
hitTolerance: 3 // use 3 pixels when selecting features, as this makes it easier to select a line
},
```
This makes it easier to select lines, rather than use the default of 1 pixel. 
Clickable features are set in classes extending from `CpsiMapview.controller.MapController` using the `clickableLayerConfigs`:
```js
clickableLayerConfigs: {
'NETWORKEDGES_WFS': {
keyField: 'ObjectId',
modelClass: 'Example.model.network.Edge', …
```
=> Allow a configurable hitTolerance

app/controller/MapController.js, test/spec/util/EditWindowOpenerMixin.spec.js
This fixes a bug where if a user clicks twice on the same vector feature, and then closes the window a feature remains on the map.
This is because a model is created on each click, and applied to the open form, but the previous model is not destroyed and so the feature is "orphaned".
=> Ensure new models are only created if they are not already open

app/form/ControllerMixin.js
A new placeholder function has been added that can be overridden in a subclass to allow parameters to be passed to a DELETE service via the querystring.
For example, in a controller that inherits from `CpsiMapview.form.ControllerMixin` `getDeleteParameters` can be added to return an object of key value pairs:
```js
getDeleteParameters: function () {
var me = this;
var myCustomParam= me.getViewModel().get('myCustomParam');
return {
myCustomParam: myCustomParam
};
}
```
The DELETE calls with then include a querystring e.g. `/object/12432?myCustomParam=abc`
This should have no effect on any existing code or classes.
=> Allow custom parameters to be passed to a DELETE service

app/controller/MapController.js, app/util/EditWindowOpenerMixin.js
Add a toast pop-up informing a user if a record fails to load when clicking on a map. Also fix a bug where if the record fails to load then the form no longer opens for valid records are `rec` is null which then causes a `TypeError: Cannot read properties of null (reading 'getId')` error.
=> Add null guard when checking for opened windows

app/controller/button/DrawingButtonController.js, app/view/button/DrawingButton.js, test/spec/controller/button/DrawingButtonController.spec.js
Allow a record to be associated with the drawing tool to avoid snapping features to themselves by checking if the current Id is the same as the snapped-to Id. 
A new `parentRecord` property is added to the button view. A record can then be bound to this property.
```js
button: {
xtype: 'cmv_drawing_button',
bind: {
disabled: '{!canDraw}',
parentRecord: '{currentRecord}',
drawLayer: '{resultLayer}' // bind the draw layer to the model's featurestore / layer
},
...
```
In the controller logic if multiple edges are found when snapping to an edge, edges with a different Id to the currently edited feature are selected. If only one edge is found then this is returned.
The use case is to allow errors in `nodeIdTo` and `nodeIdFrom` to be fixed for an edge being modified. Currently if a user …
=> Add parentRecord property to Drawing Tool for advanced snapping logic

app/view/main/Map.js
Used by some ESRI services. See this article https://support.esri.com/en-us/knowledge-base/why-does-arcgis-online-use-a-deprecated-spatial-referen-000013950
> from the REST endpoint of a hosted service, the spatial reference being used may appear as 102100 (3857). This is an expected behavior
=> Add support for EPSG:102100

app/view/main/Map.js
To avoid issues when epsg.io end points go offline (https://github.com/terrestris/BasiGX/issues/753 - "EPSG.io API endpoints will be deprecated after the 1st of February 2025"), preload the BasiGX.store.Projections store with all projections used by the BasiGX.view.panel.CoordinateMousePositionPanel. See work done in https://github.com/terrestris/BasiGX/pull/720
Without this, once the epsg.io no longer returns JSON through URLs such as https://epsg.io/?q=4326&format=json the `BasiGX.view.panel.CoordinateMousePositionPanel` will no longer display:
**Note** `"@terrestris/basigx": "3.7"` is the minimum version required to use this approach.
=> Preload all projections instead of relying on EPSG.io

app/controller/button/PermalinkButtonController.js, app/view/button/PermalinkButton.js, app/view/toolbar/MapTools.js, test/spec/view/button/PermalinkButton.spec.js
This adds a new button that opens a prompt allowing permalinks to be zoomed to - without having to reload the application, or open in a new tab.
To add the component, include `CpsiMapview.view.button.PermalinkButton` in the `requires`, and then define as follows:
```js
{
xtype: 'cmv_permalink_button',
dialogWidth: 500 // this can be used to set the width of the prompt text field
},
```
=> Add a new permalink button

app/overrides/Ext.grid.header.Container.js
After updating from ExtJS 6.7 to 7.8 ran into a bug with grid column headers.
In 6.7 this code works fine: https://docs.sencha.com/extjs/6.7.0/classic/src/Container.js-5.html
```js
getHeaderMenu: function() {
var menu = this.getMenu(),
item;
if (menu) {
item = menu.child('#columnItem');
if (item) {
return item.menu;
}
}
return null;
},
```
In 7.8 `item` is null yet the code tries to access item.menu throwing an error (when moving a column and then calling `onGroupEditToggle` in `CpsiMapview.controller.grid.GroupEditMixin`.
https://docs.sencha.com/extjs/7.8.0/classic/src/Container.js-5.html
```js
getHeaderMenu: function() {
var menu = this.getMenu(),
item;
if (menu) {
item = menu.child('#columnItem');
// ERROR - no check to see if item is null here
// TypeError: Cannot read properties of …
```
=> Add override for bug in Ext.grid.header.Container in ExtJS 7.8

app/controller/grid/GroupEditMixin.js
This PR allows overriding the serviceUrl generated from `groupEditService` property
If the property is set as is in existing codebases, the `groupEditService` value is appended to viewModel `serviceUrl` value (current behaviour)
```js
{
groupEditable: true,
groupEditService: 'isgreenway',
groupEditDataProp: 'isGreenway',
}
```
If the property starts with a forward slash, `groupEditService` value is used as is, without appending it to viewModel `serviceUrl`
```js
{
groupEditable: true,
groupEditService: '/WebServices/namespace/override',
groupEditDataProp: 'isGreenway',
}
```
=> Allow setting absolute path in groupEditService

app/form/ViewModelMixin.js
Allows records to be destroyed, without breaking bindings.
=> Add null guard check for selectStyle

app/util/MenuMixin.js, test/spec/util/MenuMixin.spec.js
This fixes an issue where the same record is opened twice. The new feature is not associated with the edit window and leaves a feature on the map even when the window is closed. To avoid this if a matching record is found in the form, the new record is destroyed.
=> Destroy any duplicate records when already opened in a window

app/controller/grid/Grid.js
Mistakes (e.g. duplicate layer keys in the default layer *.json file) result in no layer found. That trigger an exception that stop some layer names to be rendered in the layertree. This pull request manage the exception and give feedback on what the configuration error might be.
=> Added management for unfound layers
